### ISSUE TITLE
Unable to setup multiple java versions

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [actions/setup-java#105]
## Issue
When trying to use java version 9, 10, and 12 via a matrix the build fails. Error given is `No valid download found for version <version>.x and package jre. Check https://static.azul.com/zulu/bin/ for a list of valid versions or download your own jdk file and add the jdkFile argument`

I checked the link and there are no JRE versions for 9, 10, and 12 unless I missed them. 
### Steps to recreate
Create a workflow file with:
```yaml
jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-latest, windows-2016, windows-2019]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, pypy2, pypy3 ]
        java-version: [ 8, 9, 10, 11, 12, 13 ]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1.4.2
      with:
        java-version: ${{ matrix.java-version }}
        java-package: jre
```

Java version 8, 11, and 13 all completed their build fine. Is this expected because there are no versions inrepo, even though they are listed on the README or am I doing something wrong?

Link to failed run: https://github.com/Cyb3r-Jak3/html5validator/actions/runs/285144981
Job file: https://github.com/Cyb3r-Jak3/html5validator/blob/pypy3_support/.github/workflows/main.yml
