### ISSUE TITLE
maven -B deploy fails with 422 error

### ISSUE THREAD

**Issue by sblantipodi** [actions/setup-java#108]
This is my pom.xml

```
    <version>1.4.8</version>

    <distributionManagement>
        <repository>
            <id>github</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/sblantipodi/firefly_luciferin</url>
        </repository>
    </distributionManagement>
```

this my workflow:
```
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: '15.x.x'
      - name: Publish package
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

maven deploy fails with a 422 error. can you help me please?

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project FireflyLuciferin: Failed to deploy artifacts: Could not transfer artifact org.dpsoftware:FireflyLuciferin:jar:1.4.9 from/to github (https://maven.pkg.github.com/sblantipodi/firefly_luciferin): Transfer failed for https://maven.pkg.github.com/sblantipodi/firefly_luciferin/org/dpsoftware/FireflyLuciferin/1.4.9/FireflyLuciferin-1.4.9.jar 422 Unprocessable Entity -> [Help 1]
```
