### ISSUE TITLE
.java-version file support

### ISSUE THREAD

**Issue by pavolzbell** [actions/setup-java#113]
Hello, I think it would be nice to set `java-version` default value by reading `.java-version` file if it exists, what do you think?

This change is inspired by [ruby-setup](https://github.com/ruby/setup-ruby) action which already does the same with `.ruby-version` file. The use of `.java-vesion` file is popularized by [jenv](https://github.com/jenv/jenv).

**Comment by Fleshgrinder** [comment]
I found a way to add support for `.java-version` files that can act as an escape hatch for everyone who wants this functionality today:

```yaml
    - name: Export .java-version
      run: |
        java_version=11
        if [[ -f .java-version ]]; then
          java_version=$(head -1 .java-version)
        else
          echo "::error file=.java-version::Missing .java-version file, falling back to default Java version: $java_version"
        fi
        echo "JAVA_VERSION=$java_version" >>"$GITHUB_ENV"
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
```

This can of course be simplified if you use it in a repository where the `.java-version` file is always guaranteed to exist:

```yaml
    - name: Export .java-version
      run: echo "JAVA_VERSION=$(head -1 .java-version)" >>"$GITHUB_ENV"
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
```
