### ISSUE TITLE
Setup java takes much too long

### ISSUE THREAD

**Issue by joshiste** [actions/setup-java#130]
**Description:**
Currently I'm experiencing extreme slow build times because setup-java takes more than 10 minutes

**Task version:**
v1

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  
```
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
```

**Expected behavior:**
In the past the step only took a couple of seconds.

**Actual behavior:**
The step takes more than 10 minutes. May be missing caching and slow download servers?
Restarting doesn't help.
