### ISSUE TITLE
502 Bad Gateway with `v2`

### ISSUE THREAD

**Issue by sormuras** [actions/setup-java#161]
Using:

```yaml
      - name: 'Set up JDK'
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
```

Leads (sometimes) to:

![image](https://user-images.githubusercontent.com/2319838/114352389-1a99ea80-9b6c-11eb-8433-c698f8e0a915.png)

https://github.com/sormuras/bach-application-template/runs/2321248297?check_suite_focus=true

Note: Jobs running on macOs and Windows in parallel did manage to setup Java as expected.
