### ISSUE TITLE
v2 cannot setup adopt-x86 on Windows

### ISSUE THREAD

**Issue by ibauersachs** [actions/setup-java#165]
**Description:**
setup-java cannot find `adopt` with architecture `x86` on `windows-latest`. It's expected to fail for macOS (OS has only one arch) and Ubuntu (no AdoptOpenJDK builds for x86), but it should succeed on Windows.

**Task version:**
v2, 8764a52df183aa0ccea74521dfd9d506ffc7a19a

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
```
name: Setup Java
on: [push]
jobs:
  java:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-java@v2
        with:
          java-version: 8
          architecture: x86
          distribution: adopt
```

- Job as above: https://github.com/ibauersachs/gha-setup-java-v2/runs/2337615443?check_suite_focus=true
- Full matrix with v1/v2 (of adopt/zulu/8/11/mac/win/ubuntu): https://github.com/ibauersachs/gha-setup-java-v2/runs/2337562416?check_suite_focus=true

**Expected behavior:**
setup-java on Windows with adopt/x86 should succeed.

**Actual behavior:**
setup-java fails with:
```
Run actions/setup-java@v2
  with:
    java-version: 8
    architecture: x86
    distribution: adopt
    check-latest: true
    java-package: jdk
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
Trying to resolve the latest version from remote
Error: Could not find satisfied version for SemVer '8'. 
```
