### ISSUE TITLE
Two spaces instead of one

### ISSUE THREAD

**Issue by vogella** [actions/setup-java#170]
https://github.com/actions/setup-java lists examples for the usage but it look like it uses the wrong number of spaces:

The following works for me:
````

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
       distribution: 'adopt'
       java-version: 11

````
AFAICS you have one additional space before distribution and java-version
