### ISSUE TITLE
Add support for JavaFX builds

### ISSUE THREAD

**Issue by airsquared** [actions/setup-java#18]
Something like
```
- uses: actions/setup-java@v1
  with:
    java-version: '1.8'
    javafx: true
```

I believe Zulu just has `ca-fx` in the name of jdk versions with JavaFX.
