### ISSUE TITLE
Java keystore

### ISSUE THREAD

**Issue by MSzczesiak-SH** [actions/setup-java#194]
**Description:**
Could you add an option to update the keystore of this java instance ? 
in my case its stored somewhere around this place .../_work/_tool/Java_Adopt_jdk/11.0.11-9/x64/lib/security/cacerts

And it would be nice to be able to update this keystore on the fly. Because now i assume i should make a separate step that updates this keystore ? 

Could it be something like that ?

steps:
- uses: actions/checkout@v2
- uses: actions/setup-java@v2
  with:
    distribution: 'adopt' # See 'Supported distributions' for available options
    java-version: '11'
    keystore-pass: {{ secrets.KEYSTORE_PASS }}
    certificate-file: /path/cert.cer
    cert-alias: SomeAlias

This step could execute a keytool import function

keytool -import -noprompt -trustcacerts -alias SomeAlias -file path/tofile.cer -keystore  .../_work/_tool/Java_Adopt_jdk/11.0.11-9/x64/lib/security/cacerts -storepass {{ secrets.KEYSTORE_PASS }}

**Justification:**
After using this java-setup step i got SSLHandshakeException: unable to find a valid certification path to requested target 

**Are you willing to submit a PR?**
I have no idea how to contribute here....

**Comment by dmitry-shibanov** [comment]
Hello @MSzczesiak-SH. We would prefer not to add such kind of customization. The action should setup java binaries on images for its usage and further customization. As you confirmed you can use one line command to setup keystore. You can use this snippet get the output `path` from the action:
```
      - uses: actions/setup-java@v2
        id: java
        with:
          distribution: 'adopt'
          java-version: 11
          
      - name: execute a keytool import function
        shell: bash
        run:  keytool -import -noprompt -trustcacerts -alias SomeAlias -file path/tofile.cer -keystore ${{ steps.java.outputs.path }}/lib/security/cacerts -storepass {{ secrets.KEYSTORE_PASS }}
```
