### ISSUE TITLE
mvn complains  Unknown lifecycle phase ".skip=true" on Windows 

### ISSUE THREAD

**Issue by jimma** [actions/setup-java#199]
**Description:**
Github action defines the following yaml file. It fails with  Unknown lifecycle phase ".skip=true". You must specify a valid lifecycle phase or a goal in the format ....
This works on Linux.

**Task version:**
```
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name:build project 
        working-directory: ./foo
        run: |
          mvn -DskipTests=true -Denforcer.skip=true -Prelease clean install
```

**Platform:**
- [x ] Windows

**Runner type:**
- [x ] Hosted

**Repro steps:**  
A description with steps to reproduce the issue. If your have a public example or repo to share, please provide the link.

**Expected behavior:**
mvn run sueccessfully
**Actual behavior:**
 mvn failed with Unknown lifecycle phase ".skip=true". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal>
