### ISSUE TITLE
setup_java not finding Java 16 (regression)

### ISSUE THREAD

**Issue by planetf1** [actions/setup-java#203]
**Description:**
In the last hour actions using 'setup_java' are failing with:

```
 'Could not find satisfied version for SemVer '16'. '
```
**Task version:**
v2 (all that is specified)

**Platform:**
- [X] Ubuntu (default GitHub runner)
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  
Run a ci/cd workflow with the setup_java action ie https://github.com/odpi/egeria/actions/runs/1093904854

**Expected behavior:**
Build to work with java 16 (adopt)

**Actual behavior:**
Run actions/setup-java@v2
2
  with:
3
    distribution: adopt
4
    java-version: 16
5
    java-package: jdk
6
    architecture: x64
7
    check-latest: false
8
    server-id: github
9
    server-username: GITHUB_ACTOR
10
    server-password: GITHUB_TOKEN
11
    overwrite-settings: true
12
Trying to resolve the latest version from remote
13
Error: Could not find satisfied version for SemVer '16'.

**Comment by harupy** [comment]
Same here:
https://github.com/mlflow/mlflow/pull/4627/checks?check_run_id=3230769361#step:4:15

**Comment by nixel2007** [comment]
Confirm on ubuntu, macOs and windows runners

**Comment by luiszimmermann** [comment]
Same here, but with Java 8:
`Error: Could not find satisfied version for SemVer '8'.`

**Comment by chburmeister** [comment]
same for ubuntu
```
     - name: Set up JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: '15'
          distribution: 'adopt'
```
Error: Could not find satisfied version for SemVer '15'.

**Comment by floriankoch0360** [comment]
same here for JDK 13
```
- name: Set up JDK 13
  uses: actions/setup-java@v2
  with:
    java-version: '13'
    distribution: 'adopt'
```
