### ISSUE TITLE
Cache - additional paths

### ISSUE THREAD

**Issue by slawekjaranowski** [actions/setup-java#214]
**Description:**
I need more paths to cache: eg when I sued sonar I added:

```yml
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.m2/repository
            ~/.sonar/cache
```
