### ISSUE TITLE
Maven cache not working

### ISSUE THREAD

**Issue by gdrouet** [actions/setup-java#217]
**Description:**
Maven always download the dependencies even if the cache is created

**Task version:**
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

```
      - name: Setup java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          check-latest: true
          cache: 'maven'
      - run: mvn jacoco:report clean package
```

**Expected behavior:**
After a first execution, the cache should contain all my dependencies and be already on the disk for the next execution of mvn command.

**Actual behavior:**
Dependencies are still downloaded.

```
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/cba13e92-7e18-4a5b-831a-2516c488fb74/cache.tzst -P -C /home/runner/work/dst--backoffice-consumer/dst--backoffice-consumer
Cache restored successfully
Cache restored from key: setup-java-Linux-maven-5f5e8c790dbd1362edf8553421a3c7c1d75d42ca90ded98d3f4e4cd4450a9dea
```

I modified my `pom.xml` to generate a different hash but the cache is still hit. I think there is a configuration issue somewhere but don't know where.
