### ISSUE TITLE
Java 17 support?

### ISSUE THREAD

**Issue by ice1000** [actions/setup-java#229]
Are we gonna get Java 17 support for free, or do we need to do something? I tried setting `java-version` to `17` in v1 and it says:

> Error: No valid download found for version 17.x and package jdk. Check https://static.azul.com/zulu/bin/ for a list of valid versions or download your own jdk file and add the jdkFile argument

**Comment by sormuras** [comment]
In the meanwhile, you may resort to download JDK 17 via https://www.oracle.com/java/technologies/jdk-script-friendly-urls/  and use it as an input of `setup-java` ([@sormuras/bach/.github/workflows/ci.yml#L39-L50](https://github.com/sormuras/bach/blob/7683f66ae98d46d6d9b5dda1550994fd86f3c9ec/.github/workflows/ci.yml#L39-L50)).

- `setup-java@v2`

```yaml
      - name: 'Download latest JDK 17'
        run: |
          wget \
            --no-verbose \
            --directory-prefix $RUNNER_TEMP \
            https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.tar.gz
      - name: 'Set up JDK'
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: jdkfile
          jdkFile: ${{ runner.temp }}/jdk-17_linux-x64_bin.tar.gz
```

- `setup-java@v1`

Same as above without the `distribution: jdkfile` input line.

**Comment by hantsy** [comment]
Personally, I hope add `openjdk` and `oracle` as alternative providers.  

And provide *early access* build of *OpenJDK* for eager developers.

**Comment by ice1000** [comment]
> Personally, I hope add `openjdk` and `oracle` as alternative providers.  
> 
> And provide *early access* build of *OpenJDK* for eager developers.

There's `17-ea` version of the default jdk just FYI.

**Comment by sormuras** [comment]
`17` is GA...

**Comment by dmitry-shibanov** [comment]
Hello @ice1000. Thank you for your report. It looks like only 17-ea version is available for the provided distributions by the `setup-java` action. For v1 It's Zulu OpenJDK. For v2 you can see in the [Supported distributions](https://github.com/actions/setup-java#supported-distributions) section. When stable version becomes available in the API, you'll be able to use it. 
For now you can use early access versions or use a solution from @sormuras above. 
- v1
```
- name: Setup java
  uses: actions/setup-java@v1
  with:
    java-version: 17-ea
```
- v2
```
- uses: actions/setup-java@v2
  with:
    java-version: 17-ea
    distribution: adopt # zulu, temurin, 
```
Thank you for the fast response @sormuras !
For now I'm closing the issue. If you have any concerns feel free to ask us.

**Comment by ice1000** [comment]
Cool

**Comment by vhotspur** [comment]
Just in case someone needs it for Windows or Mac as well, we use the following snippet:

```yaml
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    runs-on: macos-latest
    steps:
      - name: Setup correct Java version
        uses: actions/setup-java@v2
        if: ${{ matrix.java != '17' }}
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: Fetch JDK 17
        if: ${{ matrix.java == '17' }}
        run: |
          aria2c -d ${{ runner.temp }} -o openjdk-17_macos-x64_bin.tar.gz https://download.java.net/java/GA/jdk17/0d483333a00540d886896bac774ff48b/35/GPL/openjdk-17_macos-x64_bin.tar.gz
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        if: ${{ matrix.java == '17' }}
        with:
          java-version: ${{ matrix.java }}
          distribution: jdkfile
          jdkFile: ${{ runner.temp }}/openjdk-17_macos-x64_bin.tar.gz
```

```yaml
    strategy:
      matrix:
        java: [ '8', '11' , '17' ]
    runs-on: windows-latest
    steps:
      - name: Setup correct Java version
        uses: actions/setup-java@v2
        if: ${{ matrix.java != '17' }}
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: Fetch JDK 17
        if: ${{ matrix.java == '17' }}
        run: |
          aria2c -d ${{ runner.temp }} -o openjdk-17_windows-x64_bin.zip https://download.java.net/java/GA/jdk17/0d483333a00540d886896bac774ff48b/35/GPL/openjdk-17_windows-x64_bin.zip
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        if: ${{ matrix.java == '17' }}
        with:
          java-version: ${{ matrix.java }}
          distribution: jdkfile
          jdkFile: ${{ runner.temp }}/openjdk-17_windows-x64_bin.zip
```
```
