### ISSUE TITLE
JDK17

### ISSUE THREAD

**Issue by zf1976** [actions/setup-java#233]
Can I use JDK17?

**Comment by dmitry-shibanov** [comment]
Hello @zf1976. Thank you for your report. You can install java 17 from Zulu OpenJDK distribution with this snippet:
```
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
```
For the Adopt OpenJDK distribution you can check current status [here](https://github.com/adoptium/adoptium/issues/74).

**Comment by offa** [comment]
Adoptium (= AdoptOpenJDK) has released [JDK 17](https://adoptium.net/releases.html?variant=openjdk17) today. You can use it already:

```yaml
- name: Setup jdk-17
  uses: actions/setup-java@main
  with:
    java-version: 17
    distribution: 'adopt'
```

**Comment by dmitry-shibanov** [comment]
Hello everyone. Now you can also use Eclipse Temurin java 17. You can use it with this snippet:
```
- uses: actions/setup-java@v2
  with:
    java-version: 17
    distribution: temurin
```
Thank you for your help @offa.
For now I'm closing the issue, because distributions provided by setup-java released java 17. If you have any concerns feel free to ping us.
