### ISSUE TITLE
Support for Linux/aarch64

### ISSUE THREAD

**Issue by henrik242** [actions/setup-java#236]
At least Eclipse Temurin provides `aarch64` builds of the JDK. It would be great if `setup-java` had support for it.

**Comment by dmitry-shibanov** [comment]
Hello @henrik242. Could you please try to use this snippet:
```
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
          architecture: aarch64
```
