### ISSUE TITLE
Add Support for Java 17

### ISSUE THREAD

**Issue by YNedderhoff** [actions/setup-java#238]
**Description:**
Support for Java 17, especially Temurin.

**Justification:**
It's the new LTS, many people will adopt it soon!

**Are you willing to submit a PR?**
I don't know how to, but in theory yes.

**Comment by dmitry-shibanov** [comment]
Hello @YiMysty. You can use `Temurin Java 17` by this snippet:
```
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
```
For now I'm closing the issue. If you have any concerns feel free to ping us.
