### ISSUE TITLE
Self hosted runner on GHE does not find version v2 or v2.3.1

### ISSUE THREAD

**Issue by alex-vgt** [actions/setup-java#240]
**Description:**
When I try to run an action using `setup-java`, I receive the error `Failed to resolve action download info. Error: Unable to resolve action actions/setup-java@v2, unable to find version v2`.

**Task version:**
Any version >1

**Platform:**
- [x] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Repro steps:**  
This is the action I'm trying to run:
```
- name: Setup JDK 
  uses: actions/setup-java@v2.3.1
  with:
    distribution: 'temurin'
    java-version: '11'
    cache: 'maven'
```

**Expected behavior:**
I am expecting the action to run properly.

**Actual behavior:**
The before-mentioned error.
