### ISSUE TITLE
Add ~/.gradle/jdks to cache

### ISSUE THREAD

**Issue by devminded** [actions/setup-java#245]
**Description:**
Convenience: Be able to cache JDKs for projects that uses the built in toolchain support in Gradle.

Having the action configure cache for *~/.gradle/jdks* (perhaps under a different cache-key?) in addition to *.gradle/caches, .gradle/wrapper and gradle-wrapper.properties* would avoid the unnecessary step of:
```
- name: Setup gradle JDK cache
  uses: actions/cache@v2
  with:
    path: ~/.gradle/jdks
    key: gradle-${{ runner.os }}-jdks
```

**Justification:**
Many of us have complicated multi-module builds targeting different JDK versions. For this Gradle supports toolchains that manages and downloads JDKs on demand if the required JDK versions are not found on the path. Using cache for JDKs as well is important to reduce built times. Also note that relying on matrix jobs isn't always an option and also not reproductible when doing local development builds.
