### ISSUE TITLE
certificate has expired

### ISSUE THREAD

**Issue by dready** [actions/setup-java#248]
**Description:**
Since today i get the error `certificate has expired` when running the setup-java action in my github project. It runs on ubuntu-latest.

I have changed nothing in the setup for a longer time and it did not have any problems yesterday. I was running the step with java 8, then i tried version 17 (thought, maybe the version is the problem). Still the same.

![Screenshot from 2021-11-12 13-08-20](https://user-images.githubusercontent.com/454376/141464947-dab5743a-4c41-4ee6-89a2-970682b893f7.png)

**Task version:**
v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Just ran the setup task with an error response.

**Expected behavior:**
It should just install java.

**Actual behavior:**
I get the error response "certificate has expired".

**Comment by wiebeck** [comment]
Same happens here with:
```
- name: Setup Java and Dependency Caching
  uses: actions/setup-java@v2
  with:
    distribution: 'temurin'
    java-version: '11'
    cache: 'gradle'
```
