### ISSUE TITLE
"certificate has expired" when setting up Temurin Java 11

### ISSUE THREAD

**Issue by wiebeck** [actions/setup-java#249]
**Description:**
When trying to set up a standard Java 11 Temurin distribution with Gradle caching I get an error: "certificate has expired".

**Task version:**
`actions/setup-java@v2`

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  
Our workflow fails after these standard steps:
```
steps:
  - uses: actions/checkout@v2
  - name: Setup Java and Dependency Caching
    uses: actions/setup-java@v2
    with:
      distribution: 'temurin'
      java-version: '11'
      cache: 'gradle'
```

**Expected behavior:**
The Java distribution gets set up properly.

**Actual behavior:**
From the workflow log (environment variables are custom and should be irrelevant for this step:
```
Run actions/setup-java@v2
  with:
    distribution: temurin
    java-version: 11
    cache: gradle
    java-package: jdk
    architecture: x64
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
  env:
    GITHUB_PACKAGES_ACCESS_USER: ***
    GITHUB_PACKAGES_ACCESS_TOKEN: ***
    BUILD_AND_PUSH: false
Trying to resolve the latest version from remote
Error: certificate has expired
```
