### ISSUE TITLE
Maven artifact caching is not working with maven profiles

### ISSUE THREAD

**Issue by johanblumenberg** [actions/setup-java#255]
**Description:**

The primary cache key is calculated based on a hash of all the pom files in the repository.
The problem is that different artifacts are downloaded depending on how maven is executed. For example, if different profiles are used or if different targets are invoked, different artifacts are downloaded and cached.

If multiple workflows are invoking maven in different ways, caching doesn't work between those workflows, since they use the same cache key but download different artifacts.

**Task version:**
actions/setup-java@v2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

- Create a pom file
- Create two workflows, that invoke maven with different targets, `test` and `install`

If the workflow using the `test` target is run first, a cache will be created with the downloaded artifacts for `test`. Whenever the workflow using the `package` target is run, it will find the cache from the `test` workflow, and it will have to download the additional artifacts needed for `package`.

Example:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>test</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>test</name>
</project>
```

```yaml
name: Test
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          cache: maven
      - name: Test
        run: mvn test
```

```yaml
name: Package
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          cache: maven
      - name: Package
        run: mvn package
```

**Expected behavior:**
Maven artifacts are downloaded once, the first time the jobs are run. The next time the jobs are run, everything is cached already.

**Actual behavior:**
Some artifacts are downloaded every time the `package` job is run.

**Comment by dmitry-shibanov** [comment]
Hello @johanblumenberg. Thank you for your report. We'll investigate this issue. But I am not sure we'll be able to fix it, because we need primary key to save/restore cache. The solution could be use different keys for commands, but we can't automatically identify commands.

**Comment by HannesWell** [comment]
Would it be possible to check if new artifacts were downloaded during the execution of a job and to update the cache correspondingly?
I'm not sure if this can be done efficiently or if this would lead to false positive results because Maven resolver adds some files even if they are not present. If this is a problem it maybe helps to only check for addition of files with certain endings (like `.jar`) or the creation of new directories for new plugin versions.

**Comment by HannesWell** [comment]
> If this is a problem it maybe helps to only check for addition of files with certain endings (like `.jar`) or the creation of new directories for new plugin versions.

But this could also lead to false positives if the build artifices are deployed and therefore installed in the local Maven repo (unless it could be detected that it is an installation).

**Comment by brcrista** [comment]
> The primary cache key is calculated based on a hash of all the pom files in the repository.
> The problem is that different artifacts are downloaded depending on how maven is executed. For example, if different profiles are used or if different targets are invoked, different artifacts are downloaded and cached.
> 
> If multiple workflows are invoking maven in different ways, caching doesn't work between those workflows, since they use the same cache key but download different artifacts.

So the artifacts for `test` and `package` _are_ being cached; it's just that they're using separate caches.  Is that correct?

**Comment by dsame** [comment]
@johanblumenberg Is there any reason to run the different build for the different targets with the same key?

Please take a look at the issue more closer, it has an internal contradiction: you want to cache 2 different sets of dependencies but uses the same cache key. It is expected  the very first build cache is to be used in all the following.

I suppose you would like to get a conjunction of artefacts of both builds - in this case you should use the both steps in the same build - now the cache will contain the .jar's from the both maven runs.

Does this answer help?

**Comment by johanblumenberg** [comment]
> @johanblumenberg Is there any reason to run the different build for the different targets with the same key?

Hi @dsame,

In the most basic case, I think you are right. If the maven cache would use different cache keys for different workflows, then each of the workflows would use a separate cache, and I guess the caching would work. The only drawback would perhaps be that the total cache size would grow because the caches for each workflow would have some overlap.

I don't find any way to specify a separate cache key for each job.

**Comment by johanblumenberg** [comment]
@dsame If I understand the caching correctly, you cannot share caches between PR branches. A PR branch can only use a cache created on the same PR branch, or in the target branch.

I run unit tests and integration tests in the PR branch, and after the PR is merged, I run a publishing step in the main branch.

This means that the first run on each PR would not be able to benefit from the cache, because I have set different cache keys for each job. Subsequent runs in the PR branch would use the cache.
I would have to set up a job on the main branch that would populate the cache after each commit, or perhaps once a week or couple of days.

**Comment by dsame** [comment]
@johanblumenberg 
If the cache size matters for you and you really want to share the same cache between 2 workflows for sake of having overlapped jars only once i'd advise you to utilise [actions/cache](https://github.com/actions/cache) directly with the list of the keys passed to `restore-keys` inputs

**Comment by dsame** [comment]
Hello @johanblumenberg 
The idea of java-setup cache is to make to work out of box without manual configuration. The case you have described is to be "advanced", it requires some manual configuration and the `actions/cache` should be used instead.

If i understood you right, then the snippet below does exactly that you want. Does it?

```
    steps:
      - name: Cache Maven
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/repository
          key: ${{ github.job }}-${{ hashFiles('**/pom.xml') }}
```
