### ISSUE TITLE
setup/java does not replace env variables in the settings.xml

### ISSUE THREAD

**Issue by TiomanGally** [actions/setup-java#256]
**Description:**
I am struggling to setup my settings.xml via setup/java. 
I added the username and the password for the server in my github secrets. In my workflow I set the secrets as env variables as setup/java only takes the env variables according https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#yaml-example. But when I log my settings.xml the username and password are not replaced by the value.

**Task version:**
v2.3.1

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Repro steps:**  
1. Add 2 secrets (USERNAME, PASSWORD) in your github repo
2. Add following workflow to your repository:
```
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: some-server-id
          server-username: USERNAME
          server-password: PASSWORD
      - name: Log Settings.xml
        run: cat ~/.m2/settings.xml
      - name: Build with Maven
        run: mvn clean package -s ~/.m2/settings.xml
```

**Expected behavior:**
I expect that the logged settings.xml contains my value of the secret I created for this repo. Like that:

```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>some-server-id</id>
      <username>ThatsMe</username>
      <password>superSecretPassowrd</password>
    </server>
  </servers>
</settings>
```

**Actual behavior:**
The logged settings.xml looks like that:
```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <servers>
    <server>
      <id>some-server-id</id>
      <username>${env.USERNAME}</username>
      <password>${env.PASSWORD}</password>
    </server>
  </servers>
</settings>
```
