### ISSUE TITLE
Unable to switch to Java 11

### ISSUE THREAD

**Issue by AAverin** [actions/setup-java#257]
**Description:**
Running in Github Actions

```
 - name: Set up JDK 11
    uses: actions/setup-java@v1
        with:
          java-version: 11
``` 

or

```
 - name: Set up JDK 11
    uses: actions/setup-java@v2
        with:
            distribution: 'zulu' # See 'Supported distributions' for available options
            java-version: '11'
```

and running gradle to build Android app gives an error message that Java 1.8 is still in use.

**Task version:**
Whatever github actions give

**Expected behavior:**
Java 11 should be used by the workflow

**Actual behavior:**
Java 1.8 is still used by the workflow
