### ISSUE TITLE
Maven Caching Not Working for Cross Repository Checkout

### ISSUE THREAD

**Issue by sreekanth-tf** [actions/setup-java#277]
**Description:**
Maven caching not working while we do cross repository checkout

**Task version:**
V2

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Run any maven build command on cross repository by checking out using the following code

```
uses: actions/checkout@v2
with:
  repository: myrepo/test-repo
  ref: develop
- name: Set up Java
uses: actions/setup-java@v2
with:
  java-version: '8'
  distribution: 'adopt'
  cache: 'maven'
```
**Expected behavior:**
The maven should cache, irrespective of the maven build is happening from current or cross branch

**Actual behavior:**
Maven not caching if it's cross branch maven execution
