### ISSUE TITLE
Error: java: not found

### ISSUE THREAD

**Issue by eygraber** [actions/setup-java#278]
I'm using v2.5.0 of the action, and started getting this error today.

> ./gradlew: 234: exec: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.1-12/x64/bin/java: not found

My config is:

```
      - uses: actions/setup-java@v2.5.0
        with:
              java-version: 17
              distribution: 'zulu'
```
