### ISSUE TITLE
Error: No supported distribution was found for input microsoft

### ISSUE THREAD

**Issue by shettarvinay** [actions/setup-java#299]
**Description:**
Error: No supported distribution was found for input microsoft.

**Task version:**
actions/setup-java@v2

**Platform:**
Using the runners hosted on k8s - https://github.com/actions-runner-controller/actions-runner-controller

**Runner type:**
- [x] Self-hosted

**Repro steps:**  
Adding the below steps to your workflow job 
```
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '17'
```
**Expected behavior:**
Java installation to be completed successfully. Started throwing error from last 2 days

**Actual behavior:**
Error: No supported distribution was found for input microsoft

![image](https://user-images.githubusercontent.com/8999590/156977959-1039dbc6-274e-415a-8895-13856e33b942.png)
