### ISSUE TITLE
/usr/bin/tar: ../../../../home: Cannot mkdir: Permission denied

### ISSUE THREAD

**Issue by jvermillard** [actions/setup-java#315]
**Description:**
```
Run actions/setup-java@v[2](https://github.com/xxx/xxx/runs/5850864684?check_suite_focus=true#step:5:2)
  with:
    java-version: 17
    distribution: temurin
    cache: maven
    java-package: jdk
    architecture: x64
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
Resolved Java 17.0.2+8 from tool-cache
Setting Java 17.0.2+8 as the default

Java configuration:
  Distribution: temurin
  Version: 17.0.2+8
  Path: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.2-8/x64

Creating settings.xml with server-id: github
Writing to /home/runner/.m2/settings.xml
Received 151889011 of 160277619 (94.8%), 144.9 MBs/sec
Received 160277619 of 160277619 (100.0%), 125.4 MBs/sec
Cache Size: ~15[3](https://github.com/xxxx/xxxx/runs/5850864684?check_suite_focus=true#step:5:3) MB (160277619 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/39e2ec9[4](https://github.com/xxx/xxx/runs/5850864684?check_suite_focus=true#step:5:4)-1e[5](https://github.com/xxx/xxx/runs/5850864684?check_suite_focus=true#step:5:5)9-47a0-81cd-ff4e5b0[6](https://github.com/xxx/xxx/runs/5850864684?check_suite_focus=true#step:5:6)0e[7](https://github.com/xxx/xxx/runs/5850864684?check_suite_focus=true#step:5:7)d/cache.tzst -P -C /home/runner/work/xxx/xxx
/usr/bin/tar: ../../../../home: Cannot mkdir: Permission denied
/usr/bin/tar: ../../../../home/runner/.m2/repository: Cannot mkdir: No such file or directory
/usr/bin/tar: ../../../../home: Cannot mkdir: Permission denied
/usr/bin/tar: ../../../../home/runner/.m2/repository/org: Cannot mkdir: No such file or directory
/usr/bin/tar: ../../../../home: Cannot mkdir: Permission denied
/usr/bin/tar: ../../../../home/runner/.m2/repository/org/apache: Cannot mkdir: No such file or directory
/usr/bin/tar: ../../../../home: Cannot mkdir: Permission denied
/usr/bin/tar: ../../../../home/runner/.m2/repository/org/apache/maven: Cannot mkdir: No such file or directory
/usr/bin/tar: ../../../../home: Cannot mkdir: Permission denied
/usr/bin/tar: ../../../../home/runner/.m2/repository/org/apache/maven/plugins: Cannot mkdir: No such file or directory
/usr/bin/tar: ../../../../home: Cannot mkdir: Permission denied
/usr/bin/tar: ../../../../home/runner/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin: Cannot mkdir: No such file or directory
```

**Task version:**
Specify the task version

**Platform:**
- [ X ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ X ] Hosted
- [ ] Self-hosted

**Repro steps:**  

use this workflow:
```
ame: 'validate'

on: [pull_request, workflow_dispatch]

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK and maven cache
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build
        run: mvn -T 1C -e clean package -DskipTests

      - name: Unit tests
        run: mvn -T 1C -e test
```

**Expected behavior:**
Not failing at mkdir step

**Actual behavior:**
Early failure of the action
