### ISSUE TITLE
Cannot use 19-ea due to SunCertPathBuilderException

### ISSUE THREAD

**Issue by karussell** [actions/setup-java#323]
**Description:**

We tried `19-ea` but it failed with some SunCertPathBuilderException when fetching packages from maven:

```
Failed to read artifact descriptor for org.codehaus.plexus:plexus-utils:jar:3.0: Could not transfer artifact org.codehaus.plexus:plexus-utils:pom:3.0 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/3.0/plexus-utils-3.0.pom: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

See discussion: https://github.com/actions/setup-java/issues/230#issuecomment-1109513668

I've also tried to set maven to 3.6.3 and disabled caching without success.

**Task version:**

v2 (I think?)

**Platform:**
- [x] Ubuntu

**Runner type:**
- [x] Hosted

**Repro steps:**  

See config: https://github.com/graphhopper/graphhopper/blob/jdk_release_fix/.github/workflows/push-packages.yml#L18-L35
See log https://github.com/graphhopper/graphhopper/runs/6172054216?check_suite_focus=true

**Expected behavior:**

Run the build without error like in case of the stable JDKs like 18

**Comment by dmitry-shibanov** [comment]
Sorry I pressed the wrong button

**Comment by dmitry-shibanov** [comment]
Hello @karussell. Unfortunately, I have not found the root cause of the issue for now. As a temporary workaround I can suggest to use this code:
```
      - run: |
          download_url="https://download.java.net/java/early_access/jdk19/20/GPL/openjdk-19-ea+20_linux-x64_bin.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url
      - uses: actions/setup-java@v3
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '19.0.0'
          architecture: x64
```
