### ISSUE TITLE
Fallbacks when jdk cannot be downloaded

### ISSUE THREAD

**Issue by ben-manes** [actions/setup-java#333]
**Description:**
Sometimes the JDK cannot be retrieved. In this [execution](https://github.com/ben-manes/caffeine/runs/6613492750?check_suite_focus=true#step:5:25), Cloudflare responded with a `Please Wait...` html payload which the action did not understand.

It would be nice if (a) a retry approach was implemented, (b) if fallback distributions could be set. If the execution allows for any compatible OpenJDK distribution, then this failure could be mitigated.

**Justification:**
Execution failures due to external systems, where a retry and fallback policy could allow the action to recover and not cause noise.

**Comment by e-korolevskii** [comment]
Hello @ben-manes,
Thank you very much for your request!
We are considering your feature request and will inform you about it.
Thank you for your patience.

**Comment by ben-manes** [comment]
I switched to `temurin` to take advantage of the `tool-cache` for jdk11 and for jdk18 that it is hosted on github packages (so maybe fewer cdn quirks). That was close but not enough, so I wrapped it using `wretry.action` like below. Unfortunately that skips the built-in caching due to being "loaded as a module", so that has to be done separately (e.g. via `gradle-build-action`). This might be good enough, if you prefer to document that as a workaround.

```yaml
- name: Set up JDK ${{ matrix.java }}
  uses: Wandalen/wretry.action@v1.0.20
  with:
    action: actions/setup-java@v3
    with: |
      distribution: temurin
      java-version: ${{ matrix.java }}
    attempt_limit: 3
    attempt_delay: 2000
```
