### ISSUE TITLE
Occassional cloudfront captcha when fetching Zulu 8 JDK from macOS-11

### ISSUE THREAD

**Issue by Kantis** [actions/setup-java#334]
**Description:**
Occassional cloudfront captcha when fetching Zulu 8 JDK from macOS-11 during `Trying to resolve the latest version from remote` step

[Here](https://github.com/kotest/kotest/runs/6600433246?check_suite_focus=true) one out of 4 macos builds got hit with captcha.
And another [one](https://github.com/kotest/kotest/runs/6625990511?check_suite_focus=true)..

**Task version:**
v3

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Every build in [Kotest](https://github.com/kotest/kotest) is having issues with this ATM. 

**Expected behavior:**
Zulu 8 should consistently get setup correctly on macOS

**Actual behavior:**
Zulu 8 setup sometimes fails builds due to a captcha

**Comment by mandrachek** [comment]
I'm running into this as well, but adopt jdk 11:
```yaml
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
```

Turning off the latest check should resolve the issue, at least for the time being.

**Comment by utzcoz** [comment]
I'm running into this as well with a large possibility recent days, but Zulu JDK 11.0.14 on GitHub's macOS:

```
- name: Set up JDK 11
  uses: actions/setup-java@v3
  with:
      distribution: 'zulu'
      java-version: 11.0.14
```

**Comment by albertus82** [comment]
Same here, today is impossible to build anything using Zulu.

**Comment by gciatto** [comment]
This occasionally happens to me as well, both with `adopt-hostspot` and `adopt-openj9`

**Comment by gciatto** [comment]
I guess a nice workaround would be #333

**Comment by albertus82** [comment]
A better solution might be an agreement between the providers of the JDK and GitHub so that the IP addresses of the runners can be whitelisted.

**Comment by e-korolevskii** [comment]
Hello @Kantis 
Thank you for your report!
We will investigate this issue and come back to you with updates as soon as possible!

**Comment by ImSejin** [comment]
Similar to me.

Occasionally I encounter the error on `macos-latest` and `jdk 8.0.232`.

```yml
    strategy:
      fail-fast: true
      max-parallel: 3
      matrix:
        java: [8, 8.0.232, 11, 11.0.4, 17]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: "zulu"
        cache: "maven"
```

**Comment by liamsharp** [comment]
Same for us today as well on Linux & Windows:

```
  - name: Set up JDK 17
    uses: actions/setup-java@v3
    with:
      java-version: '17.0.2'
      distribution: 'adopt'
      cache: 'maven'
```
Log here: [1_build.txt](https://github.com/actions/setup-java/files/8800118/1_build.txt)

Saw this last week when GitHub was having issues, but again this morning:

Good: 29/5/22 21:25 BST
Bad: 30/5/22 08:09 BST
Bad: 30/5/22 08:23 BST
Bad: 30/5/22 08:48 BST
Good: 30/5/22 09:28 BST

We're currently running GitHub actions in parallel with our self hosted Jenkins infrastructure with a view to moving to GitHub actions. This is the second time there has been an outage like this in the last week, is this common? Is GitHub actions reliable enough for us to move?
