### ISSUE TITLE
Run actions/setup-java@v3.3.0: Trying to resolve the latest version from remote (adopt distribution phased out)

### ISSUE THREAD

**Issue by rowi1de** [actions/setup-java#335]
**Description:**
```yaml
name: Kotlin CI with Gradle, ...

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-gradle:

    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.3.0
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
```
**Task version:**
Specify the task version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Expected behavior:**
- The action runs successfully 

**Actual behavior:**
- The action fails Run actions/setup-java@v3.3.0: Trying to resolve the latest version from remote
```html
<body>
<div>
<h1>Application is not available</h1>
<p>The application is currently not serving requests at this endpoint. It may not have been started or is still starting.</p>
<div class="alert alert-info">
<p class="info">
Possible reasons you are seeing this page:
</p>
<ul>
<li>
<strong>The host doesn't exist.</strong>
Make sure the hostname was typed correctly and that a route matching this hostname exists.
</li>
<li>
<strong>The host exists, but doesn't have a matching path.</strong>
Check if the URL path was typed correctly and that the route was created using the desired path.
</li>
<li>
<strong>Route and path matches, but all pods are down.</strong>
Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.
</li>
</ul>
</div>
</div>
</body>
```

**Comment by paoll** [comment]
Same issue with `actions/setup-java@v2`

**Comment by mxns** [comment]
Same here

**Comment by cweinberger** [comment]
Adopt API is down: https://api.adoptopenjdk.net
Status: https://status.adoptium.net/

Any workarounds?

**Comment by rowi1de** [comment]
> Adopt API is down: https://api.adoptopenjdk.net
> 
> Status: https://status.adoptium.net/
> 
> 
> 
> Any workarounds?

Ah thanks 👌🏻
use different distro?

I'm wondering if the cache is not caching the JDK itself 🤔

**Comment by anuragkusingh-kr** [comment]
I have tried all the distributions (temurin, zulu, adopt, adopt-hotspot, adopt-openj9, microsoft, corretto) using versions v2, v3 but still getting same error. Also tried zulu with version v1 but no luck there as well.

**Comment by cweinberger** [comment]
@anuragkusingh-kr for us using temurin resolved the error.

**Comment by e-korolevskii** [comment]
Hello @rowi1de 
Thank you for your report!
We will investigate this issue and come back to you with updates as soon as possible!

**Comment by rowi1de** [comment]
> I have tried all the distributions (temurin, zulu, adopt, adopt-hotspot, adopt-openj9, microsoft, corretto) using versions v2, v3 but still getting same error. Also tried zulu with version v1 but no luck there as well.

```yaml
- name: Set up JDK 17
  uses: actions/setup-java@v3.1.1
  with:
    java-version: '17'
    distribution: 'temurin'

```
works like this
