### ISSUE TITLE
Failure Trying to resolve the latest version from remote

### ISSUE THREAD

**Issue by liamsharp** [actions/setup-java#336]
**Description:**

Action fails with "Application is not available" message back in HTML in log.

**Task version:**
actions/setup-java@v3

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [X] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  

```
   name: Set up JDK 17
    uses: actions/setup-java@v3
    with:
      java-version: '17.0.2'
      distribution: 'adopt'
      cache: 'maven'
```

**Expected behavior:**
Set up Java.

**Actual behavior:**
Step fails, with an error message back as per [1_build.txt](https://github.com/actions/setup-java/files/8800161/1_build.txt)

This is similar to #334 but after looking at that log and this one it isn't Captcha related.

Time line of this working and not, to given an indication as to how long this happened for:

Good: 29/5/22 21:25 BST
Bad: 30/5/22 08:09 BST
Bad: 30/5/22 08:23 BST
Bad: 30/5/22 08:48 BST
Good: 30/5/22 09:28 BST

We're currently running GitHub actions in parallel with our self hosted Jenkins infrastructure with a few to moving to GitHub actions. This is the second time there has been an outage like this in the last week, is this common? Is GitHub actions reliable enough for us to move to?
