### ISSUE TITLE
CMake  can not found JNI

### ISSUE THREAD

**Issue by hanm2019** [actions/setup-java#341]
**Description:**
in github actions, use 
```
- name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
```
to install java jdk and in the repo CMakeLists.txt, use 
```
find_package(JNI REQUIRED)
include_directories(${JAVA_INCLUDE_PATH})
include_directories(${JAVA_INCLUDE_PATH2})
```

but meet the bug:
```
CMake Error at /home/runner/work/_temp/-1222185084/cmake-3.17.2-Linux-x86_64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY
-- Configuring incomplete, errors occurred!
See also "/home/runner/work/FPS_spinalHDL/FPS_spinalHDL/src/test/cpp/DRAMsim3/build/CMakeFiles/CMakeOutput.log".
  JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH)
```

by the way, I install CMake by:
```
    - name: Get CMake
      uses: symbitic/install-cmake@master
```
**Task version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Expected behavior:**
CMake find JNI

**Actual behavior:**
CMake  NOT find JNI
