### ISSUE TITLE
Error: getCacheEntry failed: Cache service responded with 503

### ISSUE THREAD

**Issue by adrian727** [actions/setup-java#343]
**Description:**
I am currently attempting to set up the very basic Java workflow for my projects. However, it seems to go wrong somewhere. It has worked with other projects, but the new ones seem to fail.
Excuse me if this is totally my fault and something that could easily be resolved. I tried google and nothing seems to turn up.

**Task version:**
Latest, straight from the marketplace.

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
run pipeline with

```
name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

```

**Expected behavior:**
Setup Java :)

**Actual behavior:**
```
Extracting Java archive...
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/09a0e8ce-4ea7-45ef-b011-6e29334b9412 -f /home/runner/work/_temp/e47c432c-5e30-4f6e-9d36-b371acaab142
Java 16.0.2+7 was downloaded
Setting Java 16.0.2+7 as the default
Java configuration:
  Distribution: zulu
  Version: 16.0.2+7
  Path: /opt/hostedtoolcache/Java_Zulu_jdk/16.0.2-7/x64
Creating settings.xml with server-id: github
Writing to /home/runner/.m2/settings.xml
Error: getCacheEntry failed: Cache service responded with 503
```

**Comment by JayAhn2** [comment]
I got the same issue :(

**Comment by lfgcampos** [comment]
This already happened in the past and the original issue is on the `cache` action.

Seems like the old issue was also revived by someone and they will most likely look into that!
For keeping an eye on it, please follow https://github.com/actions/cache/issues/698#issuecomment-1153555265 or potentially a new issue will be created there!

**Comment by TheBeachMaster** [comment]
Could we make this more fault tolerant to 3rd-party failures?

I'd rather download packages than no builds at all.

If this option exists kindly share.

Thanks.

**Comment by e-korolevskii** [comment]
Hello, @adrian727 

This problem is not caused by setup-java, but by cache issues. I think you can track the progress [here](https://github.com/actions/cache/issues/698) and [here](https://github.com/actions/cache/issues/820), as a temporary recommendation to restore functionality, we can suggest disabling caching.

We will keep an eye on the issue and keep this one open in case someone else bumps into the issue until it will be resolved.

Cheers!

**Comment by TheBeachMaster** [comment]
> i am getting this issue to. (since today in every test. => also in older test that was ok in the past) ![image](https://user-images.githubusercontent.com/92173565/173341013-da3b4342-0418-409c-8a11-64726cc1aa9e.png)

Disable cache in the meantime.

**Comment by BenAhrdt** [comment]
@TheBeachMaster where can i do this?

**Comment by TheBeachMaster** [comment]
> @TheBeachMaster where can i do this?
> 
> 

If this is your example workflow: 
```yml
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "gradle"
```

Remove the `cache` key
