### ISSUE TITLE
Add optional 'cache-key-file-pattern' input-argument

### ISSUE THREAD

**Issue by HannesWell** [actions/setup-java#345]
**Description:**
Add an optional input-argument to specify the patterns of files considered for hashing to compute the cache-key, for example named `cache-key-file-pattern`, that could be used like in the following example:
```
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        cache-key-file-pattern: "'**/pom.xml', '**/*.target'"
```
and would be equivalent to
```
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '**/*.target') }}
        restore-keys: |
          ${{ runner.os }}-maven-
```

**Justification:**

For _Eclipse-Plugin_ projects most of the time a so called _Target-Platform_ is used that specifies all available dependencies a project can be build against. Such a _Target-Platform_ is defined in *.target files. _Eclipse-Plugin_ projects are usually build with Maven and Tycho, a set of Maven-Plugins and extensions designed to build Eclipse-Plugin projects. But usually dependencies are not specified in the project's pom.xml (often a Eclipse Plugin project does not even has an explicit pom.xml). When building Eclipse-Plugin projects with Maven+Tycho (and a *.target-file) a change in the *.target file can cause other dependencies to be fetched into the local Maven-repo (e.g. in the build machines .m2 folder) than those that are already fetched in previous builds and are therefore cached (e.g. a newer version).

As a consequence the default key file pattern `hashFiles('**/pom.xml')`, which is used by this action is not sufficient for our use-cases and we work-around that by using `actions/cache` explicitly like in the equivalent case shown above.
Because I assume that you probably don't want to include Eclipse specific files into the pattern and others maybe also just want to use a customized file pattern and are happy with the rest of the maven or gradle setup, I'm proposing the additional input argument. 

**Are you willing to submit a PR?**

In general yes, but given that I'm not so much familiar with Java/Type-script and this only requires to loop through an additional input parameter (I my simplified thinking) I think you can do it much faster than I can. :)
