### ISSUE TITLE
Cannot find GPG secret key during sign

### ISSUE THREAD

**Issue by piotrooo** [actions/setup-java#355]
**Description:**
Cannot sign artifact. Error:

```
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
```

**Task version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
I set secrets in repo.

![secrets](https://user-images.githubusercontent.com/2005054/179090265-4f2c1ab3-fb93-476a-85f8-e5cb66db9133.png)

I have following steps in action (https://github.com/semver4j/semver4j/blob/main/.github/workflows/release.yml):
```yml
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set version
        uses: actions/github-script@v4
        id: set_version
        with:
          script: |
            const tagName = context.payload.release.tag_name
            const version = tagName.replace('v', '')
            core.setOutput('version', version)
      - name: Build with Apache Maven
        run: mvn --batch-mode package

      - name: Publish to GitHub Packages Apache Maven
        run: mvn --batch-mode deploy -Drevision=${{ steps.set_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Publish package to Apache Maven Central
        run: mvn --batch-mode deploy -Drevision=${{ steps.set_version.outputs.version }}
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
```

And here is my [pom.xml](https://github.com/semver4j/semver4j/blob/main/pom.xml);
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-gpg-plugin</artifactId>
    <version>3.0.1</version>
    <executions>
        <execution>
            <id>sign-artifacts</id>
            <phase>verify</phase>
            <goals>
                <goal>sign</goal>
            </goals>
            <configuration>
                <gpgArguments>
                    <arg>--pinentry-mode</arg>
                    <arg>loopback</arg>
                </gpgArguments>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Expected behavior:**
Signed artifact ready to push.

**Actual behavior:**
Errors:

```
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
```

Link to [failure action](https://github.com/semver4j/semver4j/actions/runs/2673239836).

**Comment by piotrooo** [comment]
The problem is with github publish step.

```
- name: Publish to GitHub Packages Apache Maven
  run: mvn --batch-mode deploy -Drevision=${{ steps.set_version.outputs.version }}
  env:
    GITHUB_TOKEN: ${{ github.token }}
```

Without this step everything is ok.
How should be configured this step? Is any bug in documentation?

**Comment by dsame** [comment]
Hello @piotrooo,

I did a quick review for few obvious obstacles but none of them seems to relate to the problem, but i have no understanding why does one step uses `MAVEN_GPG_PASSPHRASE` for `mvn deploy` and another only `GITHUB_TOKEN`.

I would expect you need to have the step like one below following the login of the rest of pipelin

```
- name: Publish to GitHub Packages Apache Maven
  run: mvn --batch-mode deploy -Drevision=${{ steps.set_version.outputs.version }}
  env:
    MAVEN_GPG_PASSPHRASE: ${{ github.token }}
 ```
 
 Please add more info to let me know where i am wrong.

**Comment by dsame** [comment]
Hello @piotrooo 

The root cause of the problem is the step to build the maven project is used before the `setup-java` step, this is why the secret file is not created yet.

In case if really need such flow you have to create it by yourself with the snippet like this one:

```
      - name: Import GPG private key
        env:
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        run: |
          f=`mktemp`
          echo "${MAVEN_GPG_PRIVATE_KEY}" > "$f"
          gpg --batch --import-options import-show --import "$f"
```

Also to utilize the passphrase you must pass it to maven explicitly
```
      - name: Build with Apache Maven
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: mvn --batch-mode verify gpg:sign -Dgpg.passphrase=$MAVEN_GPG_PASSPHRASE
```

Sample pipeline: https://github.com/akv-demo/setup-java-test/actions/runs/2734660995

Also this part of pom.xml does not seem to be necessary 
```
            <configuration>
                <gpgArguments>
                    <arg>--pinentry-mode</arg>
                    <arg>loopback</arg>
                </gpgArguments>
            </configuration>
```
See the step "[plugin-configuration](https://github.com/akv-demo/setup-java-test/runs/7506988247?check_suite_focus=true)"


Does this solve the issue?
