### ISSUE TITLE
Cache `/root/.m2/repository`

### ISSUE THREAD

**Issue by tristan957** [actions/setup-java#356]
**Description:**
I use containers (Ubuntu, Fedora, Almalinux) in GitHub Actions. In my workflows, I am using this action. In the "Post Setup Java" step, I see a warning about a path validation error.

What I have discovered is that the Maven local repository path by default is `/root/.m2/repository`, so `~/.m2/repository` doesn't exist.

**Justification:**
This is a very hard issue to discover, and since this path seems to the default on many images, or at least the ones I am using, it should be cached in addition to the usual `~/.m2/repository`.

https://github.com/actions/cache/issues/814

**Are you willing to submit a PR?**
Potentially.

Alternatively, allow us as users to configure the cache path ourselves.

**Comment by dsame** [comment]
hello @tristan957 
Thanks for sharing your use case, as a quick solution there's an action for custom caching https://github.com/actions/cache
Meanwhile we will investigate the issue and make a  decision about adding the directory to the automatic cache.

**Comment by tristan957** [comment]
Yep, I think I'll probably implement that today now that I know what the problem is. Thanks!

**Comment by dsame** [comment]
@tristan957 from this  "path by default is /root/.m2/repository" i could suggest there's `sudo` or `su` call somewhere.

**Comment by tristan957** [comment]
That would make sense. Here is a minimal GitHub Actions file that can recreate the path.

```yaml
jobs:
  fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:36

    steps:
      - run: |
          dnf install maven
          mvn help:evaluate -Dexpression=settings.localRepository | grep 'm2/repository'
```

Notice how you don't need `sudo` for `dnf`. Seems like GitHub drops you in as a privileged user within the container.
