### ISSUE TITLE
java.io.FileNotFoundException: /home/runner/.m2/settings-security.xml (No such file or directory)

### ISSUE THREAD

**Issue by mr3** [actions/setup-java#357]
**Description:**
Error:  Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:deploy (injected-nexus-deploy) on project arex-common: Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:deploy failed: Cannot decipher credentials to be used with Nexus! org.sonatype.plexus.components.sec.dispatcher.shaded.SecDispatcherException: java.io.FileNotFoundException: /home/runner/.m2/settings-security.xml (No such file or directory) -> [Help 1]

I have checked similar issues: #91, but did not fix this problem.

**Task version:**
`actions/setup-java@v3`

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  
The problem github action workflow runs: https://github.com/arextest/arex-common/actions/runs/2675590433

**Expected behavior:**
The job would complete successfully.

**Actual behavior:**
An error is printed and the step and job are failed.

**Comment by mr3** [comment]
I closed this issue. The reason is that I did not copy the gpg private key completely. 

Refer to this link to output the gpg private key: [How to Sign and Release to The Central Repository with GitHub Actions](https://gist.github.com/sualeh/ae78dc16123899d7942bc38baba5203c)

**Comment by mr3** [comment]
Please ignore ths issue. I have fixed it, misconfiguration.

**Comment by AB027GT** [comment]
Can you please post solution how you resolve it. I am having same issue

**Comment by ronnyfm** [comment]
> Please ignore ths issue. I have fixed it, misconfiguration.

Can you share what did you change to fix it? Thanks.

**Comment by DQinYuan** [comment]
Can you please post solution how you resolve it. I am having same issue

**Comment by outscale-mdr** [comment]
Hello,

I did have the same issue. The problem was that I misread the documentation. `server-username` and `server-password` are actually the name of the environment variable (and not the value) that contain repectively the username and the password. (see [here](https://github.com/actions/setup-java?tab=readme-ov-file#maven-options))

Instead of having:
```yaml
- name: Set up Apache Maven Central
      uses: actions/setup-java@v4
      with: # running setup-java again overwrites the settings.xml
        ...
        server-username: ${{secrets.username}}
```
Do this:
```yaml
- name: Set up Apache Maven Central
      uses: actions/setup-java@v4
      with: # running setup-java again overwrites the settings.xml
        ...
        server-username: THIS_IS_A_VARIABLE_USERNAME
- name: Publish
      run: mvn deploy
      env:
        THIS_IS_A_VARIABLE_USERNAME: ${{secrets.username}}
```
