### ISSUE TITLE
Allow custom target directory for exploding `jdkFile` into

### ISSUE THREAD

**Issue by sormuras** [actions/setup-java#359]
**Description:**
Introduce an optional input for specifying a custom target directory for exploding a `jdkFile` into.

**Justification:**
Installing multiple JDKs that share the same JDK feature release number (like `19`) is not possible at the moment.

For example, after downloading two JDK archives that both are based on JDK 19, the second run of `setup-java@v3` detects that a Java 19 is already installed and uses it; instead of extracting the second JDK archive into a new and different directory:

```yml
    - name: 'Install custom JDK 19'
      uses: actions/setup-java@v3
      with:
        distribution: jdkfile
        jdkFile: .../openjdk-19-jextract+2-3_linux-x64_bin.tar.gz
        java-version: 19.0.0+0-jextract

    - name: 'Install full JDK 19'
      uses: actions/setup-java@v3
      with:
        distribution: jdkfile
        jdkFile: .../openjdk-19-ea+33_linux-x64_bin.tar.gz
        java-version: 19
```

The output of the second run reads like:

```yml
Run actions/setup-java@v3
  with:
    java-version: 19
    distribution: jdkfile
    jdkFile: .../openjdk-19-ea+33_linux-x64_bin.tar.gz
    java-package: jdk
    architecture: x64
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_jdkfile_jdk/19.0.0-0-jextract/x64
Resolved Java 19.0.0+0-jextract from tool-cache
Setting Java 19.0.0+0-jextract as default
```

**Expectation:**

With a custom target directory specified for each run (`openjdk-19-jextract+2-3` and `openjdk-19-ea+33`), there would be two dedicated JDK installations. Like:

- /opt/hostedtoolcache/Java_jdkfile_jdk/openjdk-19-jextract+2-3/x64
- /opt/hostedtoolcache/Java_jdkfile_jdk/openjdk-19-ea+33/x64

**Work-around:**
Pass fake values to `java-version` in order to generated dedicated target directories. See https://github.com/oracle-actions/setup-java/issues/34 for details.

**Comment by denismakogon** [comment]
For some reason,`setup-java action uses _ONLY_ major version as a distinct factor which makes it impossible to install JDKs with the same major version, but with a different minor, micro, and build number. `jextract` is a good example showing that it's not possible to have it installed alongside with the JDK 19 because underlying `jextract` Java runtime has the same major version.

**Comment by dsame** [comment]
Hello @denismakogon,
While we investigating the exact problem and task flow, can you please give us a hint would it be a workaround if the `java-version` in `Install full JDK 19` set to the explicit value?

I mean this:
```
    - name: 'Install full JDK 19'
      uses: actions/setup-java@v3
      with:
        distribution: jdkfile
        jdkFile: .../openjdk-19-ea+33_linux-x64_bin.tar.gz
        java-version: 19-ea
```
