### ISSUE TITLE
No supported distribution was found for input corretto

### ISSUE THREAD

**Issue by byF** [actions/setup-java#360]
**Description:**
`corretto` should be officially supported, but the action can't find it
**Task version:**
v3

**Platform:**
Amazon Linux 2

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Repro steps:**  
```yaml
- uses: actions/setup-java@v3
  with:
    distribution: "corretto"
    java-version: "17"
```

**Expected behavior:**
The action installs Corretto OpenJDK

**Actual behavior:**
The action fails with
```
No supported distribution was found for input corretto
```
