### ISSUE TITLE
Retrieving wrong binary release when using container (alpine, temurin)

### ISSUE THREAD

**Issue by fwendland** [actions/setup-java#374]
**Description:**
I'm using a container based on Alpine Linux to run steps in a workflow (i.e. using `jobs.<job_id>.container`; cf. workflow in _Repro steps_). With the `setup-java` action I retrieve a Temurin distribution of Java. However, the action retrieves the binary distribution for `linux` rather than `alpine-linux`.
```
Run actions/setup-java@v3
/usr/bin/docker exec  2ea31e8b381847497dc4bd1bc9d3a9562c25534780653c610f871630fe8695a9 sh -c "cat /etc/*release | grep ^ID"
Trying to resolve the latest version from remote
Resolved latest version as 11.0.16+101
Trying to download...
Downloading Java 11.0.16+101 (Temurin-Hotspot) from https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.16.1%2B1/OpenJDK11U-jdk_x64_linux_hotspot_11.0.16.1_1.tar.gz ...
Extracting Java archive...
/bin/tar xz -C /__w/_temp/c1f0cca2-150d-42f4-8016-6783ade0d24e -f /__w/_temp/b3a90d2d-45c9-4d6b-95f0-0966b426844a
Java 11.0.16+101 was downloaded
Setting Java 11.0.16+101 as the default
Java configuration:
  Distribution: temurin
  Version: 11.0.16+101
  Path: /__t/Java_Temurin-Hotspot_jdk/11.0.16-101/x64
Creating settings.xml with server-id: github
Writing to /github/home/.m2/settings.xml
```
Trying to run `java` fails due to problems with the libraries:
```
Run echo -n "which java: " && which java
  echo -n "which java: " && which java
  echo -n "ls -la: " && ls -la $(which java)
  echo -n "ldd: " && ldd $(which java)
  echo -n "java --version: " && java --version
  shell: sh -e {0}
  env:
    JAVA_HOME: /__t/Java_Temurin-Hotspot_jdk/11.0.16-101/x64
which java: /__t/Java_Temurin-Hotspot_jdk/11.0.16-101/x64/bin/java
ls -la: -rwxr-xr-x    1 root     root         12768 Aug 24 12:46 /__t/Java_Temurin-Hotspot_jdk/11.0.16-101/x64/bin/java
ldd: 	/lib64/ld-linux-x86-64.so.2 (0x7f517246d000)
Error relocating /__t/Java_Temurin-Hotspot_jdk/11.0.16-101/x64/bin/../lib/jli/libjli.so: __strdup: symbol not found
	libz.so.1 => /lib/libz.so.1 (0x7f5172250000)
Error relocating /__t/Java_Temurin-Hotspot_jdk/11.0.16-101/x64/bin/../lib/jli/libjli.so: __rawmemchr: symbol not found
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f517246d000)
	libjli.so => /__t/Java_Temurin-Hotspot_jdk/11.0.16-101/x64/bin/../lib/jli/libjli.so (0x7f517203f000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f517246d000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f517246d000)
Error: Process completed with exit code 127.
```

**Task version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
1. Use the following workflow definition:
```
name: Use GitHub actions in container

on:
  workflow_dispatch: 

jobs:
  run:
    runs-on: ubuntu-latest
    container: 
      image: alpine
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
      - name: View Java tools
        run: |
          echo -n "which java: " && which java
          echo -n "ls -la: " && ls -la $(which java)
          echo -n "ldd: " && ldd $(which java)
          echo -n "java --version: " && java --version
```
2. Execute workflow manually

**Expected behavior:**
`setup-java` recognizes the Linux distro in the container and downloads the `alpine-linux` binary distribution of Temurin. The run of the workflow succeeds without errors. The last step executes `java` successfully and prints the current version.

**Actual behavior:**
`setup-java` identifies only `linux` and downloads the `linux` binary distribution of Temurin. The workflow run fails caused by the last step. Trying to run `java` returns exit code `127`.
