### ISSUE TITLE
Maven cache not found but no diagnostics

### ISSUE THREAD

**Issue by toolforger** [actions/setup-java#417]
**Description:**
We're using actions/setup-java@v3 but each build reports "maven cache is not found" (hence it re-downloads everything, then caches everything in the post-run action, but the cache still isn't found in the next run).
There is no clue as to why it does not find the cache.

I am aware that much of this might have to be taken to the cache action's maintainers, but I'm reporting here first to investigate what's on actions/setup-java and what's on cache.

**Task version:**
actions/setup-java@v3
This should be setup-java@v3.6.0 currently (the run log does not tell, unfortunately).

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
The following .github/workflows/release.yml file should reproduce this behaviour:
```
name: Publish package to GitHub Packages
on:
    release:
        types: [ created ]
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    distribution: temurin
                    java-version: '17'
                    cache: maven
            -   name: publish-maven-artifact
                run: ./mvnw --batch-mode deploy
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

BTW this affects all our projects, this is just the simplest GH workflow that I have.

**Expected behavior:**
a) It should find the cache from the previous run.
b) If it does not find the cache from the previous run, it should log how it tried to locate the cache. (This might have to be taken to the maintainers of the cache action.)
c) Further, if the cache is not found, actions/setup-java should report how it called the cache action, so the issue can be investigated by the user, or taken to the maintainers of the cache action.

**Actual behavior:**
a) It does not find the cache from the previous run.
b) c) There is no diagnostic output.
