### ISSUE TITLE
Derive architecture from underlying runner machine architecture

### ISSUE THREAD

**Issue by bbednarek** [actions/setup-java#418]
**Description:**
The target architecture parameter has default value: `x64`. It would be nice to derive it from underlying runner machine architecture e.g. if the runners run on `ARM64` then default value would be `aarch64`.

**Justification:**
The aim is to keep the github runner pipelines agnostic to the underlying architecture of the machine where it runs e.g. we are migrating from `X64` to `ARM64` machines and it would be great to keep generic pipeline with a following step
```
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
```
instead of specifying `architecture` parameter. Such a change would be backward compatible, because the default value `x64` would stay if underlying machine is `X64`.

Alternative solution would be to accept `RUNNER_ARCH` [environment variable](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables) as default, but even now supplying it without additional mapping is not possible, because  possible values (`X86`, `X64`, `ARM`, or `ARM64`) are not compatible with `architecture` parameter. 

**Are you willing to submit a PR?**
I am not familiar with Typescript, but I can try :)
