### ISSUE TITLE
No way to configure maven version in actions/setup-java 

### ISSUE THREAD

**Issue by ichinna** [actions/setup-java#457]
**Description:**
Maven @3.9.0 introduced plugin breakage.  And I don't see a way I can use a particular version of maven with setup-java GitHub Actions.  So, can you provide information on how to use/configure a particular version when I use `actions/setup-java` in a GitHub pipeline?  For reference look at this Maven [changelog](https://maven.apache.org/docs/3.9.0/release-notes.html)

**Task version:**
v1 v2 v3 (All versions)

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [x] Self-hosted

**Repro steps:**  
Try to use a maven plugin in your pom.xml.  And when running it using maven@3.9.0, it fails to download that plugin.

**Expected behavior:**
A way to configure a particular version of maven in `actions/setup-java@v*`

**Actual behavior:**

**Comment by IvanZosimov** [comment]
Hi, @ichinna 👋 Thanks for the issue, we will take a look at it and get back to you with updates.

**Comment by maxandersen** [comment]
+1 on this as it is a regular occurrence that maven minor updates does break things faster than plugin can get updates.

**Comment by maxandersen** [comment]
#40 indicates maven is not being provided by setup-java thus they won't add config for it ? Not following how that works.

**Comment by joelittlejohn** [comment]
As a workaround, I've switched to using https://github.com/s4u/setup-maven-action. Here's an example:

```yaml
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          checkout-fetch-depth: 0
          java-version: 8
          java-distribution: temurin
          maven-version: 3.8.7
```
