### ISSUE TITLE
Whether cache jdk is supported?

### ISSUE THREAD

**Issue by seepine** [actions/setup-java#470]
**Description:**
yml
```
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
          cache: maven
```
And need to download again every time, like
```
Trying to resolve the latest version from remote
Resolved latest version as 8.0.362+9
Trying to download...
Downloading Java 8.0.362+9 (Zulu) from https://cdn.azul.com/zulu/bin/zulu8.68.0.21-ca-jdk8.0.362-linux_x64.tar.gz ...
```

**Justification:**
Cache jdk can accelerate execution

**Are you willing to submit a PR?**
