### ISSUE TITLE
When Trying to run mvn package --file pom.xml getting error from repo.maven.org

### ISSUE THREAD

**Issue by vishalvrv9** [actions/setup-java#485]
**Description:**
The actions/setup-java@v3 was working until today afternoon. Same workflow.yml. But since 5pm EDT today, it is giving an error saying

```
Error:      Non-resolvable import POM: Could not transfer artifact org.springframework.session:spring-session-bom:pom:2021.2.0 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/org/springframework/session/spring-session-bom/2021.2.0/spring-session-bom-2021.2.0.pom @ org.springframework.boot:spring-boot-dependencies:2.7.9-SNAPSHOT, /home/runner/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.7.9-SNAPSHOT/spring-boot-dependencies-2.7.9-SNAPSHOT.pom, line 2781, column 19: Unknown host repo.maven.apache.org -> [Help 2]
```
I am able to run the mvn same command on my local machine without any errors. The maven version on my local and the workflow also appears to be the same. 

**Task version:**
actions/setup-java@v3
JDK 19
Maven 3.8.8

**Platform:**
Ubuntu
**Runner type:**
Hosted

**Repro steps:**  
Running the below action yields error.
```
name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
```

**Expected behavior:**
mvn build should succeed

**Actual behavior:**
gives the error mentioned above

EDIT: Formatting
