### ISSUE TITLE
Support OpenJDK in order to use -ea versions

### ISSUE THREAD

**Issue by gortiz** [actions/setup-java#492]
**Description:**
As we know, OpenJDK used to be the place where free JRE and JDKs were downloaded from, but in the new model consumers should use other vendors like temurin, microsoft, etc. This is true for all versions but the EA, which are not packaged by these vendors and therefore they should be downloaded from OpenJDK*. 

As said in [OpenJDK docker page](https://hub.docker.com/_/openjdk):
> This image is officially deprecated and all users are recommended to find and use suitable replacements ASAP. Some examples of other Official Image alternatives (listed in alphabetical order with no intentional or implied preference):

`<list of publishers>`

> The only tags which will continue to receive updates beyond July 2022 will be Early Access builds (which are sourced from [jdk.java.net](https://jdk.java.net/)), as those are not published/supported by any of the above projects.

* This is not 100% correct. Some vendors like Azul do offer EA versions in their webpage, but they are not included in the endpoint this action calls.

**Justification:**
In order to support newest JVMs as fast as possible, it is very useful to be able to compile and test libraries and applications using the JDK that is being development. This is specially important in a moment like this when the release in EA is going to be LTS and will include tons of improvements and new features compared to the last LTS.

**Comment by IvanZosimov** [comment]
Hi, @gortiz 👋 Thanks for the feature request! We will think about it and let you know if it's approved to be implemented or not.

**Comment by BohdanM-AVISPL** [comment]
Hello, I am wondering why there are no support of OpenJDK at all, not even Early Access? It seems to have proper license -- GPL+classpath extension.

**Comment by sormuras** [comment]
As an alternative, you're invited to use https://github.com/oracle-actions/setup-java to install Early Access releases of the JDK:

```yaml
steps:
  - name: 'Set up latest JDK EA from jdk.java.net'
    uses: oracle-actions/setup-java@v1
    with:
      website: jdk.java.net
      release: EA
```

Note that `oracle-actions/setup-java` does use `actions/setup-java` to perform the actual installation and configuration.

**Comment by akurtakov** [comment]
What is the status here?

**Comment by brunoborges** [comment]
The core need here — using OpenJDK **Early Access** builds from [jdk.java.net](https://jdk.java.net/) that aren't packaged by the supported vendor distributions — is already achievable today via the `jdkfile` distribution, without a dedicated EA endpoint.

Download the EA archive in a prior step and point `setup-java` at it with the `jdkFile` input; `setup-java` then handles extraction, installation, caching, and `JAVA_HOME` setup:

```yaml
steps:
- run: |
    download_url="https://download.java.net/java/early_access/jdk25/36/GPL/openjdk-25-ea+36_linux-x64_bin.tar.gz"
    wget -O $RUNNER_TEMP/java_package.tar.gz $download_url
- uses: actions/setup-java@v5
  with:
    distribution: 'jdkfile'
    jdkFile: ${{ runner.temp }}/java_package.tar.gz
    java-version: '25-ea'
    architecture: x64
- run: java --version
```

This is the same guidance given in #612. We're also adding an explicit Early Access note + example to the advanced docs in #1058.

If you'd prefer `setup-java` to resolve and download EA builds for you automatically, [`oracle-actions/setup-java`](https://github.com/oracle-actions/setup-java) wraps this action and supports that directly:

```yaml
steps:
  - uses: oracle-actions/setup-java@v1
    with:
      website: jdk.java.net
      release: EA
```

Since the EA use case is covered by the existing `jdkfile` feature (and the upcoming docs in #1058), I'm closing this issue. If there's interest in a native `jdkUrl`/EA-resolving input built into this action, please open a focused feature request for that specific enhancement.
