### ISSUE TITLE
Gradle cache not working on windows

### ISSUE THREAD

**Issue by ennioVisco** [actions/setup-java#514]
**Description:**
The gradle cache is never found:
<img width="456" alt="image" src="https://github.com/actions/setup-java/assets/740025/3d3c7c1d-412f-418b-8a41-8ee2ad823683">

**Task version:**
`@3`
**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
```yml
   - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
```
**Expected behavior:**
At some point in later jobs/executions, the cache should be found.
