### ISSUE TITLE
JRE_HOME is not setting up

### ISSUE THREAD

**Issue by RanabirChakraborty** [actions/setup-java#524]
**Description:**
After setting up JRE when checking for JRE_HOME, it's showing nothing. Does JRE_HOME actually being set? If so then how to check?

**Task version:**
Version v3

**Platform:**
- [ ] Ubuntu

**Repro steps:**  
Setup steps - https://github.com/wildfly/wildfly/compare/main...RanabirChakraborty:wildfly:test?expand=1
Result - https://github.com/RanabirChakraborty/wildfly/actions/runs/5842594565/job/15843860980

**Expected behavior:**
It should set up JRE_HOME. But it's showing blank like below . Please check here - https://github.com/RanabirChakraborty/wildfly/actions/runs/5842594565/job/15843860980#step:5:1

```
Run echo "JRE_HOME is "
JRE_HOME is 
```

**Comment by marko-zivic-93** [comment]
Hello @RanabirChakraborty 
We will take a look at this issue and come back to you as soon as we have some updates. 🙂

**Comment by IvanZosimov** [comment]
Hi, @RanabirChakraborty 👋 Currently our action sets up only `JAVA_HOME` environment variable. If some JRE is installed, the value of `JAVA_HOME` will contain path to installed JRE. If this behavior is not suitable for your use case, please provide us with the feedback.

**Comment by IvanZosimov** [comment]
Just a gentle ping, @RanabirChakraborty 📟

**Comment by IvanZosimov** [comment]
Just a gentle ping, @RanabirChakraborty 📟

**Comment by RanabirChakraborty** [comment]
Hello @IvanZosimov Sorry I was on holiday. 
For our case, we want to use JRE to test our repository through GitHub actions, but that's the challenge we are facing. Even if we try to use the below yaml 

```
- name: Setup JRE ${{ matrix.java }} for building
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'
          java-package: 'jre'
```
it's not installing setup and we are unable to detect JAVA_HOME as the JRE path.
so my question is can you please explain to me how to install JRE through GitHub action so that I can get the required result?
