### ISSUE TITLE
Installation location env vars only have limited use

### ISSUE THREAD

**Issue by dmlloyd** [actions/setup-java#537]
**Description:**
Define an additional environment variable for each installed JDK, `JAVA_HOME_##` where `##` is the version number of the JDK, without the architecture string.

Alternatively, allow the name of an additional env var to be explicitly specified for each installed version. Perhaps by allowing the JDK versions to be given as a list with `version` and `env-name` subkeys.

**Justification:**
Right now the environment variable name for each installed JDK contains the architecture of the corresponding JDK.  This works fine if you are specifying the architecture as an argument to the action.

However, our main use case for specifying more than one JDK is to simply install different *versions* for our multi-version build testing, possibly in conjunction with an OS or CPU architecture matrix build. In this situation, the environment variable name cannot really be predicted. We have to choose, for example, `JAVA_HOME_11_X64` or `JAVA_HOME_11_AARCH64` on our build command line. This requires duplication of jobs and filtering based on CPU architecture and so forth so that we can use the correct env var based on the CPU architecture. This at least partially defeats the purpose of automatic detection in the first place.

By having the simpler env var, we can use the same build steps across all CPU architectures, for example:

```yaml
      - uses: actions/setup-java@v3
        name: set up jdk versions
        with:
          distribution: temurin
          java-version: |
            11
            17
      # 17 is the default version
      # ...
      # now this works on x86, x64, aarch64, etc.
      - name: run the test on 11 and 17
        run: |
          cd project-dir
          mvn -B -ntp install -Djava11.home=${{env.JAVA_HOME_11}}
```

**Are you willing to submit a PR?**
I think that would be outside of my wheelhouse unfortunately. It would be better for someone with the appropriate skills to handle this.
