### ISSUE TITLE
Add jdk 21

### ISSUE THREAD

**Issue by sleski** [actions/setup-java#541]
**Description:**
19.09.2023 new LTS was released - jdk 21, please add possibility to use it via github-actions.

**Justification:**
new Java LTS was released.

**Are you willing to submit a PR?**

**Comment by sleski** [comment]
My mistake, we do not need this.

**Comment by hertg** [comment]
For anybody stumbling here. The JDK 21 has not yet been released for the `temurin` distribution. For the time being, the early access build can be used by specifying `21-ea`.

```yaml
- uses: actions/setup-java@v3
  with:
    distribution: temurin
    java-version: 21-ea
```

https://adoptium.net/blog/2023/08/early-access-builds/
