### ISSUE TITLE
README incorrectly states "cache-dependency-path" can be used

### ISSUE THREAD

**Issue by jmhodges** [actions/setup-java#571]
**Description:**
The README's [Usage section](https://github.com/actions/setup-java/?tab=readme-ov-file#usage) says that the parameter `cache-dependency-path` can be used to set which pom files to cache from.

However, on a fresh repo with no prior GitHub Action runs adding that will cause GHA to emit a warning (not an error) saying that parameter doesn't exist:

```
Warning: Unexpected input(s) 'cache-dependency-path', valid inputs are ['java-version', 'java-version-file', 'distribution', 'java-package', 'architecture', 'jdkFile', 'check-latest', 'server-id', 'server-username', 'server-password', 'settings-path', 'overwrite-settings', 'gpg-private-key', 'gpg-passphrase', 'cache', 'job-status', 'token', 'mvn-toolchain-id', 'mvn-toolchain-vendor']
```

**Task version:**
I don't know what this is. This is with setup-java@v3. (Does that help?)

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  

```
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: |
          java/pom.xml
```

(with a pom at `./java/pom.xml` but this error happens before that's checked)

**Expected behavior:**
No warnings or errors and the caching should work as documented

**Actual behavior:**
It warns about the documented parameter not existing
