### ISSUE TITLE
Unable to setup temurin with gitea actions runner

### ISSUE THREAD

**Issue by Renari** [actions/setup-java#584]
**Description:**
![image](https://github.com/actions/setup-java/assets/1839179/f8308534-eb21-49ba-ac7c-22752f0ac89c)
```yml
- name: Setup JDK 
  uses: actions/setup-java@v4
  with:
    distribution: 'temurin'
    java-version: '17'
```

This is using the Gitea actions runner, so I'm unsure if this is exclusives to this setup.

**Task version:**
4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Repro steps:**  
```yml
- name: Setup JDK 
  uses: actions/setup-java@v4
  with:
    distribution: 'temurin'
    java-version: '17'
```

**Expected behavior:**
JDK to find temurin jdk 17

**Actual behavior:**
No distributions found
