### ISSUE TITLE
how do i use the "install-multiple-jdks" in the Github action

### ISSUE THREAD

**Issue by angold5** [actions/setup-java#586]
**Description:**
How do i use the new version of java in the github action
https://github.com/actions/setup-java#install-multiple-jdks

```
    steps:

        uses: actions/setup-java@v4
        with:
          distribution: '<distribution>'
          java-version: 17
      - run: java HelloWorldApp.java
```

```
      - name: Sonar scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info
working-directory: ./my-app/HelloWorldFunction
```

**Justification:**
i dont know how to use it

**Are you willing to submit a PR?**

**Comment by aparnajyothi-y** [comment]
Hello @angold5 
Thank you for reporting this issue, We will investigate it and come back to you as soon as we have some information.

**Comment by AndreiLepkovTR** [comment]
I cannot assign JAVA_HOME variable to switch Java versions. It shows empty value. How it should be done?
```
      - name: Set up multiple JDKs
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: |
            21
            11
      - name: Some java work that requires JAVA 21
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_21_x64 }}
        run: java HelloWorldApp.java
```

**Comment by brunoborges** [comment]
This is a usage question, so answering and closing it here. To install multiple JDKs and have a later step use a specific one, pass a multi-line `java-version` — `setup-java` installs each and exports `JAVA_HOME_<major>_<arch>` for every version (the **last** one becomes the active `JAVA_HOME`/`PATH`):

```yaml
steps:
  - uses: actions/setup-java@v4
    with:
      distribution: 'temurin'
      java-version: |
        8
        11
        17
  - name: Use Java 11 explicitly
    run: \$JAVA_HOME_11_X64/bin/java -version
  - name: Default (last installed = 17)
    run: java -version
```

See the docs: https://github.com/actions/setup-java?tab=readme-ov-file#install-multiple-jdks

Note: this installs multiple **versions** of one distribution. Installing multiple **distributions** in one step is a separate feature request, now tracked in #1049. For questions, the [GitHub Actions community discussions](https://github.com/orgs/community/discussions/categories/actions) are also a good venue.
