### ISSUE TITLE
Error: connect ETIMEDOU

### ISSUE THREAD

**Issue by ansereb** [actions/setup-java#589]
**Description:**
Today i start receiving `Error: connect ETIMEDOUT 104.18.0.192:443` on my multiple workflows runned on Github-hosted runner  so it shouldn't be a problem with internet connectivity.

**Task version:**
@v1

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
```
- name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 17
```
