### ISSUE TITLE
Not in gzip format

### ISSUE THREAD

**Issue by lwxu25** [actions/setup-java#590]
Original issue: #23 

---

Hi, reopening this issue as to not necro the old one, seems like this is a resurface of the same issue with v2.

This is produced by the following configuration to set up JDK 8:

```yaml
uses: actions/setup-java@v2
with:
  distribution: 'jdkfile'
  jdkFile: jdk-8u351-linux-x64.tar.gz
  java-version: '8.0.351'
  architecture: x64
```

The error I get is the following:

```console
Run actions/setup-java@v2
Java 8.0.351 was not found in tool-cache. Trying to unpack JDK file...
Extracting Java from '/home/runner/work/battlecode24/battlecode24/jdk-8u351-linux-x64.tar.gz'
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/bb77d015-d00b-4b4c-82a1-752be766c813 -f /home/runner/work/battlecode24/battlecode24/jdk-8u351-linux-x64.tar.gz

gzip: stdin: not in gzip format
/usr/bin/tar: Child returned status 1
/usr/bin/tar: Error is not recoverable: exiting now
Error: The process '/usr/bin/tar' failed with exit code 2
```

&nbsp;
Edit: Resolved. Seems like the organisation firewall corrupted the gzip upload.
