### ISSUE TITLE
When comparing v4 to v3, significant time difference in the post run process

### ISSUE THREAD

**Issue by kdkdhoho** [actions/setup-java#591]
**Description:**
When comparing v4 to v3, we noticed a significant time difference in the post run process.

**Task version:**
Photo reference

**Platform:**
- [x] Ubuntu (actions)
- [x] macOS (local)
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Below are the results using v4.
[Result Page of v4](https://github.com/8-Sprinters/ListyWave-back/actions/runs/7753323010)
<img width="1288" alt="image" src="https://github.com/actions/setup-java/assets/66300965/9470b39b-a80a-451c-994b-c0dbcf3f89ad">
<img width="424" alt="image" src="https://github.com/actions/setup-java/assets/66300965/ef793f20-9e19-41cc-9048-955b086d3fcb">

Below are the results using v3.
[Result Page of v3](https://github.com/8-Sprinters/ListyWave-back/actions/runs/7753459097/job/21144808813)
<img width="1294" alt="image" src="https://github.com/actions/setup-java/assets/66300965/971c24b1-2b9d-4e34-81da-af67e8aa32b3">
<img width="425" alt="image" src="https://github.com/actions/setup-java/assets/66300965/c32efdcf-ad9a-4126-9d8a-a3a87d072bf6">

**Expected behavior:**
There is no time difference between the two.

**Actual behavior:**
There was a significant time difference.

**Comment by brenoavm** [comment]
I'm having the same issue when running the following actions:

```
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: "oracle"
        cache: "maven"
```

The principal difference for me seems to be on the maven cache, but I don't know if this is the cause of the time difference.
I have updated the action version only because of nodejs16 deprecation.

V3:
![setup-java-v3](https://github.com/actions/setup-java/assets/2013524/6ca4a232-a0af-43fc-a74b-df483b7b8f26)

V4:
![setup-java-v4](https://github.com/actions/setup-java/assets/2013524/f7b93de6-ba5f-4895-a932-36e39bb9f9bd)
