### ISSUE TITLE
Using GPG on V4, the gpg importer will always take 3 minutes

### ISSUE THREAD

**Issue by GedMarc** [actions/setup-java#600]
**Description:**
When configuring and using setup-java on v4 with gpg parameters, the step that imports the gpg key will always take 3 minutes

**Task version:**
V4

**Platform:**
- [ X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ X] Hosted
- [ ] Self-hosted

**Repro steps:**  
Create a working GPG setup using setup-java on v3. Update the version to v4. The task will now take 3 minutes. 

Working 
```
       - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'oracle'
          #server-id: github_token
          #settings-path: ${{ github.workspace }}
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
```
Affected
```
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'oracle'
          #server-id: github_token
          #settings-path: ${{ github.workspace }}
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: secrets.GPG_PASSPHRASE
```
**Expected behavior:**
The same as in V3, when the task is complete the job must continue immediately. 

**Actual behavior:**
The step waits for 3 minutes on any workflow for the task to complete
