### ISSUE TITLE
setup-java post action caching for v4 is slower than v3

### ISSUE THREAD

**Issue by htpaf** [actions/setup-java#601]
**Description:**
When switching from setup-java v3 to v4 the post run part is significantly slower.

**Task version:**
v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

Slow:
```
jobs:
  verify:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: run maven
        run: |
          mvn -B --settings .mvn/settings.xml verify
        shell: bash

```
![image](https://github.com/actions/setup-java/assets/135227466/ff42f60a-3597-441a-890e-e8367c7d2330)

---
Fast:
```
jobs:
  verify:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: run maven
        run: |
          mvn -B --settings .mvn/settings.xml verify
        shell: bash
``` 
![image](https://github.com/actions/setup-java/assets/135227466/9320c7ea-e63b-4e83-bc3b-e2a58c2f1aa1)

**Expected behavior:**
v4 should have the same speed as v3. 
Both executions had no cache hits and the amount of data was approx 30MB.

**Actual behavior:**
v4 is in this case orders of magnitude slower than v3.

**Additional information:**

I have seen that actions setup-node https://github.com/actions/setup-node/issues/878
and setup-ruby https://github.com/ruby/setup-ruby/issues/543 have had the same problem.
It seems that it had to do with the upgrade of the actions/cache version.

I think their solution was to exit the process manually after caching is complete as otherwise the job simply hangs until some timeout.

After looking at this repo for a very short time **my guess** is that perhaps somewhere 
here -> https://github.com/actions/setup-java/blob/9704b39bf258b59bc04b50fa2dd55e9ed76b47a8/src/cache.ts#L150
a ` process.exit(0)` could solve the problem (as I said, I'm only guessing based on the node and ruby solutions).
