### ISSUE TITLE
Pull packages from GitHub private packages, return status: 401 Unauthorized and 'parent.relativePath' points at wrong local POM

### ISSUE THREAD

**Issue by ParryQiu** [actions/setup-java#602]
**Description:**

Attempting to configure an action to fetch packages from a repository within the same organization results in an authentication error.
The error is encountered when downloading dependencies from GitHub's Maven package repository.
Despite correct configuration, the process fails with a 401 Unauthorized status, indicating an issue with authentication.

```
Downloading from github: https://maven.pkg.github.com/xx/xx/xx/xx/xx/xx.pom

Error: ] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM ... authentication failed for https://maven.pkg.github.com/, status: 401 Unauthorized and 'parent.relativePath' points at wrong local POM @ line 7, column 13
```

**Task version:**
actions/setup-java@v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

Below is the YAML configuration for the GitHub Action used to deploy Maven packages upon a release event.

```
name: Maven Package Deploy

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
          server-id: github
          server-username: xxx
          server-password: ${{ secrets.GITHUB_TOKEN }}

...

```

Additionally, here's the relevant section from the pom.xml file that specifies the repository configuration:

```
...

    <repositories>
        <repository>
            <id>github</id>
            <name>GitHub OWNER Apache Maven Packages</name>
            <url>https://maven.pkg.github.com/xx/xxxxxx</url>
        </repository>
    </repositories>

...

```

**Expected behavior:**
The action should successfully pull the required packages from the GitHub Maven repository without encountering authentication issues.

**Actual behavior:**
The action fails with a 401 Unauthorized error when attempting to fetch packages, indicating a failure in authentication.
