### ISSUE TITLE
mvn not found on self-hosted runners

### ISSUE THREAD

**Issue by fernandezpablo85** [actions/setup-java#61]
When running:

```yaml
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
```

On a `self-hosted` runner, the build fails saying:

```
1457fa28-9216-4663-b693-074afad52b42.sh: line 1: mvn: command not found
```

It works fine on github-hosted runners.
