### ISSUE TITLE
GPG Key import successfully, but "No secret key" when maven deploy

### ISSUE THREAD

**Issue by DQinYuan** [actions/setup-java#619]
[Job Url](https://github.com/alibaba/QLExpress/actions/runs/8589366589/job/23535421554)

config:

```yaml
name: Maven Central Repo Deployment
on:
  release:
    types: [released, prereleased]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v2
      - name: Set up Maven Central Repo
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          server-id: sonatype-nexus-staging
          server-username: 'OSSRH_USER'
          server-password: 'OSSRH_PASSWORD'
          gpg-passphrase:  'MAVEN_GPG_PASSPHRASE'
          gpg-private-key: ${{ secrets.GPG_SECRET }}
      - name: debug settings.xml
        run: cat /home/runner/.m2/settings.xml
      - name: Publish to Maven Central Repo
        run: mvn clean deploy --batch-mode --activate-profiles deploy
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
```

gpg private key imported successfully:

![image](https://github.com/actions/setup-java/assets/23725000/0cac1408-2cec-4993-afc9-0ed5af40ac64)

Bug maven depoly failed with "No secret key":

![image](https://github.com/actions/setup-java/assets/23725000/fc06b1b4-682a-4dfc-862e-52207ef3d760)
