### ISSUE TITLE
Can't install temurin java 8 for macos

### ISSUE THREAD

**Issue by DorianMazur** [actions/setup-java#625]
**Description:**
My workflow is failing because java 8 is no longer available for macos -> https://github.com/dherault/serverless-offline/actions/runs/8815659321/job/24201682104?pr=1779

https://api.adoptium.net/v3/assets/version/%5B1.0,9.0%5D?project=jdk&vendor=adoptium&heap_size=normal&sort_method=DEFAULT&sort_order=DESC&os=mac&architecture=aarch64&image_type=jdk&release_type=ga&jvm_impl=hotspot&page_size=20

**Platform:**
- [ ] Ubuntu
- [x] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
On macos arm64 runner:
```
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "8"
```

**Expected behavior:**
It should be possible to install java 8 on macos

**Actual behavior:**
It's not possible to install java 8 on macos
