### ISSUE TITLE
Gradle caching post-task consistently fails on Windows with "device or resource busy"

### ISSUE THREAD

**Issue by nhubbard** [actions/setup-java#633]
**Description:**
On Windows runners, my `setup-java` consistently shows read errors for the following files in the `.gradle` folder:

* `.gradle/caches/8.7/fileContent/fileContent.lock`
* `.gradle/caches/8.7/fileHashes/fileHashes.lock`
* `.gradle/caches/8.7/generated-gradle-jars/generated-gradle-jars.lock`
* `.gradle/caches/8.7/javaCompile/javaCompile.lock`
* `.gradle/caches/jars-9/jars-9.lock`
* `.gradle/caches/journal-1/journal-1.lock`
* `.gradle/caches/modules-2/modules-2.lock`

It also happened in older builds with Gradle 8.6.

**Task version:**

`actions/setup-java@v4`

Workflow file is as follows:

```yaml
name: Konf CI
on: [ push ]
jobs:
  build:
    name: Build on JDK ${{ matrix.java_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Only covers Java 21 because the publishing plugin doesn't work on lesser versions
        java_version: [ 21 ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java_version }}
          cache: "gradle"
      - name: Build and Test with Gradle
        env:
          OSS_USER_TOKEN: ${{ secrets.OSS_USER_TOKEN }}
          OSS_USER_PASSWORD: ${{ secrets.OSS_USER_PASSWORD }}
        run: ./gradlew build
      - name: Report Coveralls (Linux)
        if: startsWith(runner.os, 'Linux')
        run: curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls report build/reports/kover/report.xml
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: Report Coveralls (Windows)
        if: startsWith(runner.os, 'Windows')
        run: |
          Invoke-WebRequest -Uri "https://github.com/coverallsapp/coverage-reporter/releases/latest/download/coveralls-windows.zip" -OutFile "coveralls-windows.zip"
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          [System.IO.Compression.ZipFile]::ExtractToDirectory("coveralls-windows.zip", ".")
          Remove-Item "coveralls-windows.zip"
          Start-Process -FilePath ".\coveralls.exe" -ArgumentList "report build/reports/kover/report.xml" -NoNewWindow -Wait
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: Report Coveralls (macOS)
        if: startsWith(runner.os, 'macOS')
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          brew tap coverallsapp/coveralls --quiet
          brew install coveralls --quiet
          coveralls report build/reports/kover/report.xml
```

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:** 

I already provided the exact workflow file above, but the repository is here: https://github.com/nhubbard/konf

Here are some example successful workflow runs where this issue is logged:

* https://github.com/nhubbard/konf/actions/runs/9115686424/job/25062581278
* https://github.com/nhubbard/konf/actions/runs/9044702615/job/24853637509
* https://github.com/nhubbard/konf/actions/runs/9019442520/job/24782324790

**Expected behavior:**

The cache is successfully generated for restoration on the next build with the Windows runner.

**Actual behavior:**

A `tar` error is reported under the "Post Set up JDK 21" action:

```
Post job cleanup.
"C:\Program Files\Git\usr\bin\tar.exe" --posix -cf cache.tzst --exclude cache.tzst -P -C D:/a/konf/konf --files-from manifest.txt --force-local --use-compress-program "zstd -T0"
/usr/bin/tar: C\:/Users/runneradmin/.gradle/caches/8.6/fileContent/fileContent.lock: Read error at byte 0, while reading 38 bytes: Device or resource busy
/usr/bin/tar: C\:/Users/runneradmin/.gradle/caches/8.6/fileHashes/fileHashes.lock: Read error at byte 0, while reading 38 bytes: Device or resource busy
/usr/bin/tar: C\:/Users/runneradmin/.gradle/caches/8.6/generated-gradle-jars/generated-gradle-jars.lock: Read error at byte 0, while reading 38 bytes: Device or resource busy
/usr/bin/tar: C\:/Users/runneradmin/.gradle/caches/8.6/javaCompile/javaCompile.lock: Read error at byte 0, while reading 38 bytes: Device or resource busy
/usr/bin/tar: C\:/Users/runneradmin/.gradle/caches/jars-9/jars-9.lock: Read error at byte 0, while reading 38 bytes: Device or resource busy
/usr/bin/tar: C\:/Users/runneradmin/.gradle/caches/journal-1/journal-1.lock: Read error at byte 0, while reading 38 bytes: Device or resource busy
/usr/bin/tar: C\:/Users/runneradmin/.gradle/caches/modules-[2](https://github.com/nhubbard/konf/actions/runs/9019442520/job/24782324790#step:7:2)/modules-2.lock: Read error at byte 0, while reading 38 bytes: Device or resource busy
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Failed to save: "C:\Program failed with error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2
Cache saved with the key: setup-java-Windows-gradle-0b89a5[3]
```

Despite the "cache saved with the key" message, it doesn't actually save the cache correctly.
