### ISSUE TITLE
Unable to parse Java version on Ubuntu runner

### ISSUE THREAD

**Issue by corrideat** [actions/setup-java#641]
**Description:**
Unable to parse Java version on Ubuntu runner.

**Task version:**
99b8673ff64fbf99d8d325f52d9a5bdedb8483e9

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  

```yaml
  task:
    name: 'Ubuntu (Node 20, Deno 1.40, Java 21)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
        with:
          distribution: 'dragonwell'
          java-version: '21'
```

**Expected behavior:**
Java is set up

**Actual behavior:**

```
Run actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
  with:
    distribution: dragonwell
    java-version: 21
    java-package: jdk
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
    token: ***
Installed distributions
  Trying to resolve the latest version from remote
  Error: Invalid Version: 17.0.1+0.1+12
```
