### ISSUE TITLE
Specify distribution via java-version-file

### ISSUE THREAD

**Issue by tsawada** [actions/setup-java#646]
Currently, setup-java requires `distribution` field. However, one can specify a distribution in `.java-version` thus the distribution input field can be redundant or even confusing when these two disagree.

It'd be great if `distribution` field is optional and can be configured via `.java-version` file.

**Comment by priya-kinthali** [comment]
Hello @tsawada 👋,
Thank you for this feature request. We will investigate it and get back to you as soon as we have some feedback.

**Comment by skateball** [comment]
Hi @tsawada ,
have you checked to not use a distribution in the yml file?

To me the following should work and use a recent temurin 21 release
```yaml
steps:
- uses: actions/checkout@v4
- uses: actions/setup-java@v4
  with:
    java-version: '21'
- run: java HelloWorldApp.java
```

Regards Christian
