### ISSUE TITLE
CRAC JDK is not usable as criu needs SUID permissions to work

### ISSUE THREAD

**Issue by snicoll** [actions/setup-java#660]
**Description:**
I am trying to use CRAC in GitHub Actions. With the following definition:

```
 - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          java-package: 'jdk+crac'
          distribution: 'zulu'
```

I can't use `criu` as it's missing `SUID` permissions. Courtesy of @wkia, it would work if the archive was extracted using `sudo tar xz`.

There's not much, but here it is failing: https://github.com/spring-projects/spring-lifecycle-smoke-tests/actions/runs/10032558509/job/27724454193

With a manual setup (see https://github.com/spring-projects/spring-lifecycle-smoke-tests/commit/efd6ee22b9eafdf1276739574ff57d67e1156bba), it is working: https://github.com/spring-projects/spring-lifecycle-smoke-tests/actions/runs/10039511315

**Task version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

**Expected behavior:**
`criu` works out-of-the-box

**Actual behavior:**
`criu` fails as it's missing SUID permissions
