### ISSUE TITLE
Action is not compatible with latest versions of maven-gpg-plugin

### ISSUE THREAD

**Issue by loesak** [actions/setup-java#668]
**Description:**
This action is no longer fully compatible with later versions of the `maven-gpg-plugin`.

The action takes the variable `gpg-passphrase` which is expected to be the environment variable that holds the value of the secret key, and sets the maven variable `gpg.passphrase` in the `settings.xml` file to the value of the environment variable. The original expectation here is that the passphrase will be provided via `pinentry` during signing. In later versions of the `maven-pgp-plugin`, `pinentry` was disabled and the plugin variable `passphrase` was deprecated.

It is now expected that the passphrase is taken from an environment variable directly by the plugin. The plugin expects the environment variable name to be either the default of `MAVEN_GPG_PASSPHRASE` or provided via the configuration property of `passphraseEnvName`.

If you used this action with the `maven-gpg-plugin` version `1.6` and set the value for action variable `gpg-passphrase` to anything other than the default, it would work. However, after upgrading to a later version (e.g. `3.2.4`) the build would fail.

If the value for the action variable `gpg-passphrase` was set to the expected default of `MAVEN_GPG_PASSPHRASE` (as is shown in GitHub example documentation), then the build would continue to work.

Another workaround if wanting to use an environment variable name other than default is to omit the action variable `gpg-passphrase` from the action configuration and specify the alternative variable name in the maven plugin configuration using the configuration variable name `passphraseEnvName`

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-gpg-plugin</artifactId>
    <version>3.2.4</version>
    <configuration>
        <bestPractices>true</bestPractices>
        <passphraseEnvName>MY_GPG_PASSPHRASE</passphraseEnvName>
    </configuration>
    <executions>
        <execution>
            <id>sign-artifacts</id>
            <phase>verify</phase>
            <goals>
                <goal>sign</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

Also note that the documentation for advance usage related to GPG signing contains documentation about setting pinentry to loopback. This also no longer working in later versions of the `maven-gpg-plugin`.

**Task version:**
All

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:** 
Specify a different environment variable name for `gpg-passphrase` than `MAVEN_GPG_PASSPHRASE`

```yml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        server-id: maven
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MY_GPG_PASSPHRASE

    - name: Publish to Apache Maven Central
      run: mvn deploy
      env:
        MAVEN_USERNAME: maven_username123
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        MY_GPG_PASSPHRASE: ${{ secrets.MY_GPG_PASSPHRASE }}
```

And use version `3.2.4` of the `maven-gpg-plugin` as such:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-gpg-plugin</artifactId>
    <version>3.2.4</version>
    <executions>
        <execution>
            <id>sign-artifacts</id>
            <phase>verify</phase>
            <goals>
                <goal>sign</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Expected behavior:**
Build runs successfully

**Actual behavior:**
Build fails with error during signing.

**Comment by priyagupta108** [comment]
Hi @loesak 👋,
Thank you for reporting this! We will look into and come back to you with the details!

**Comment by aparnajyothi-y** [comment]
Hello @loesak, Thank you for creating this issue. We tried to reproduce it on Ubuntu and macOS environments, but were unable to do so. We used a different environment variable name for the GPG passphrase than MAVEN_GPG_PASSPHRASE with the maven-gpg-plugin version 3.2.4. The process was successful by setting pinentry to loopback without adding passphraseEnvName. Please find the screenshots for reference.
It would be helpful if you could provide additional details like repro link from a public repository to check and assist, as we are unable to reproduce it on the Ubuntu runner.

```
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-gpg-plugin</artifactId>
<version>3.1.0</version>
<executions>
<execution>
<id>sign-artifacts</id>
<phase>verify</phase>
<goals>
<goal>sign</goal>
</goals>
</execution>
</executions>

<configuration>
							
<gpgArguments>
<arg>--pinentry-mode</arg>
<arg>loopback</arg>
</gpgArguments>
							
</configuration>
</plugin>
```
```
name: Set up Apache Maven Central
      uses: actions/setup-java@v4
      with: # running setup-java again overwrites the settings.xml
        distribution: 'sapmachine'
        java-version: ${{ matrix.java-version }}
        server-id: central # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME # env variable for username in deploy
        server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: MY_GPG_PASSPHRASE # env variable for GPG private key passphrase

    - name: Publish to Apache Maven Central
      run: mvn -P release --batch-mode deploy -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME}}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN}}
        MY_GPG_PASSPHRASE: ${{ secrets.MY_GPG_PASSPHRASE }}
```
<img width="1263" alt="Screenshot 2024-08-30 at 6 48 43 PM" src="https://github.com/user-attachments/assets/c2444ab5-206e-4e34-88ea-792a8d69d5cc">
