### ISSUE TITLE
Java executable not found depending on container

### ISSUE THREAD

**Issue by abbasyadollahi** [actions/setup-java#678]
**Description:**
I have a simplified action which sets up Java inside of a container. Depending on the container used, I get an error because it fails to run the the installed Java executable, even though it seems to exist. The Java version doesn't seem to matter.

**Task version:**
v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  
Here's a barebones example of the steps in the GitHub action, where `test-docker` fails and `test-ubuntu` works.

```yaml
...
jobs:
  test-docker:
    runs-on: ubuntu-latest
    container: docker:cli
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Execute Java
        run: |
          which java
          type java
          echo $JAVA_HOME
          echo $PATH
          java --help

  test-ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Install docker and docker-compose
        run: |
          apt -y update 
          apt -y install sudo curl
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh ./get-docker.sh
          apt-get install docker-compose-plugin
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Execute Java
        run: |
          which java
          type java
          echo $JAVA_HOME
          echo $PATH
          java --help
```

**Expected behavior:**
I expect both jobs to successfully install the `java` executable (which they seem to do) and be able to execute it.

**Actual behavior:**
The `test-docker` job seems to install the `java` library properly, but doesn't seem to be able to execute it. On the other hand, the `test-ubuntu` job installs the `java` library properly and is able to run the `java` executable as expected. In both cases, the `java` lib seems to exists on disk, but the job using the `docker:cli` image as its container can't find the `java` executable. Below is an excerpt of the output of the `Execute Java` step of each job.

test-docker
```
/__t/Java_Temurin-Hotspot_jdk/11.0.24-8/x64/bin/java
java is /__t/Java_Temurin-Hotspot_jdk/11.0.24-8/x64/bin/java
/__t/Java_Temurin-Hotspot_jdk/11.0.24-8/x64
/__t/Java_Temurin-Hotspot_jdk/11.0.24-8/x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/__w/_temp/24f7e9c6-9173-452f-b7b0-833ce68b877a.sh: line 5: /__t/Java_Temurin-Hotspot_jdk/11.0.24-8/x64/bin/java: not found
```

test-ubuntu
```
/__t/Java_Temurin-Hotspot_jdk/11.0.24-8/x64/bin/java
java is /__t/Java_Temurin-Hotspot_jdk/11.0.24-8/x64/bin/java
/__t/Java_Temurin-Hotspot_jdk/11.0.24-8/x64
/__t/Java_Temurin-Hotspot_jdk/11.0.24-8/x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Usage: java [options] <mainclass> [args...]
           (to execute a class)
...
```
