### ISSUE TITLE
Java 17 failing with "Could not find satisfied version for SemVer '17'"

### ISSUE THREAD

**Issue by edenman** [actions/setup-java#692]
**Description:**
This was working fine until today.

**Task version:**
v4

**Platform:**
- Ubuntu
```
Current runner version: '2.320.0'
Runner name: 'android-16-core_d8ba276e3d05'
Runner group name: 'Android-CI'
Machine name: 'runner'
Operating System
  Ubuntu
  22.04.5
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20241006.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20241006.1/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20241006.1
```

**Runner type:**
- Hosted

**Repro steps:**  
Our config 
```
            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    distribution: 'adopt'
                    java-version: 17
```

**Expected behavior:**
Install

**Actual behavior:**
Not installed
```
Run actions/setup-java@v4
  with:
    distribution: adopt
    java-version: 17
    java-package: jdk
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
    token: ***
  env:
    PACKAGE_USERNAME: ***
    PACKAGE_TOKEN: ***
Installed distributions
  Trying to resolve the latest version from remote
  Error: Could not find satisfied version for SemVer '17'. 
```

**Comment by gplessis** [comment]
Looks like https://api.adoptopenjdk.net/ is currently in bad shape, throwing a 404.
https://www.eclipsestatus.io/ shows degraded services and an upcoming maintenance.

**Comment by edenman** [comment]
maybe `adopt` removed 17? switching to temurin seems to work if anybody else hits this

**Comment by genev** [comment]
We're seeing the same issue and the timing matches the downtime here: https://api.adoptopenjdk.net, like mentioned above.

**Comment by ahatzz11** [comment]
We've confirmed that zulu is also working after swapping to that over `adopt`: 

```yaml
    - name: Set up JDK 17
      id: setup-java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17
```
