### ISSUE TITLE
`setup-java@v4` setup for sbt failing on Linux with `sbt: command not found`

### ISSUE THREAD

**Issue by dnkanga** [actions/setup-java#694]
**Description:**
This seemingly broke overnight, i'm attempting to setup the build with this

```
jobs:
  unit-test-with-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Compile and run tests
        run: sbt clean coverage test coverageReport
```

and the build is failing with

```
Run sbt clean coverage test coverageReport
  sbt clean coverage test coverageReport
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_TOKEN: ***
    ORG_TOKEN: ***
    JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.24-8/x64
    JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.24-8/x64
/home/runner/work/_temp/b7c25d22-b1b1-4c67-b34a-c29a4ed01426.sh: line 1: sbt: command not found
Error: Process completed with exit code 127.
```

**Platform:**
- [ X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ X] Hosted
- [ ] Self-hosted
