### ISSUE TITLE
Could not find GraalVM for SemVer 17

### ISSUE THREAD

**Issue by violetagg** [actions/setup-java#700]
**Description:**
The issue below started to appear on 16.10.2024 without any changes in the project

```
Trying to resolve the latest version from remote
  Error: Could not find GraalVM for SemVer 17
```

**Task version:**
v4

**Platform:**
- [X] Ubuntu
- [X] macOS
- [X] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  
https://github.com/reactor/reactor-netty/actions/runs/11357786129

```
      - name: Set up GraalVM 17
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73
        with:
            distribution: 'graalvm'
            java-version: '17'
```

**Expected behavior:**
GraalVM to be installed

**Actual behavior:**
GraalVM is not installed
