### ISSUE TITLE
actions/setup-java@v1: version: 9, better control for exact JDK version

### ISSUE THREAD

**Issue by mP1** [actions/setup-java#702]
My repo includes the following fragment to select a JDK 9 runtime and eventually run my unit tests.

```
      - name: Set up JDK 9
        uses: actions/setup-java@v1
        with:
          java-version: 9
```

My tests include assertions made using data from `java.util.Locale`, which can and does change in minor versions of the JRE.

Locally i use 9.0.4 to study and create the expected assertions for my tests. These tests are failing in github because the runtime is not using 9.0.4 but something slightly different java 9 which has different locale data.

I would like to be able to request EXACTLY `java-version: 9.0.4`.

I would also be good if the step printed automatically printed `java -version`

**Comment by priya-kinthali** [comment]
Hello @mP1 👋,
Thank you for reporting this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by priyagupta108** [comment]
Hi @mP1,
We recommend updating your workflow to use the latest version (v4) of `actions/setup-java`. This version will automatically print the Java version in use, helping you verify the JDK version. You can specify the exact version using the `java-version` input. For more details, please refer to the [documentation](https://github.com/actions/setup-java?tab=readme-ov-file#supported-version-syntax).

Here's an example configuration to set up JDK 9.0.4:

```yaml
steps:
- uses: actions/checkout@v4
- uses: actions/setup-java@v4
  with:
    distribution: 'zulu' # See 'Supported distributions' for available options
    java-version: '9.0.4'
```

Please let us know if you encounter any further issues.
