### ISSUE TITLE
./gradlew build is 'Compiling and testing with Java 21' although actions/setup-java@v4 is setting Java 17

### ISSUE THREAD

**Issue by GabeGiro** [actions/setup-java#714]
**Description:**
./gradlew build is 'Compiling and testing with Java 21' after actions/setup-java@v4 is setting Java 17.

I tried a lot of things:
- Zulu and Temurin
- manually downloading JDK 17 in one of the steps of the script
- task versions v3 and v4
- [workaround with update-alternatives](https://github.com/actions/setup-java/issues/701#issuecomment-2467293400)
- more info in [GitHub support ticket](https://support.github.com/ticket/personal/0/3139796) for whoever can open it

**Task version:**
v3 and v4

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Repro steps:**  

Use this ci.yml in your Android project:
```
name: CI

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

#      - name: Cache Gradle packages
#        uses: actions/cache@v4
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper/
#          key: ${{ runner.os }}-gradle-v1-${{ hashFiles('**/build.gradle', '**/build.gradle.kts', '**/settings.gradle', '**/settings.gradle.kts', '**/gradle.lockfile') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-v1-

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Notify Success
        if: success()
        run: echo "Build and tests passed!"

      - name: Notify Failure
        if: failure()
        run: echo "Build or tests failed!"

```

Note: I commented out the cache for the purpose of making sure that I'm not reusing gradle files

**Expected behavior:**
Build with Gradle step should show:
`Compiling and testing with Java 17`

**Actual behavior:**
Build with Gradle step shows:
`Compiling and testing with Java 21`

**Comment by mahalakshmi-rekadi** [comment]
Hello @GabeGiro,
Thank you for reporting this issue. We will investigate it and get back to you as soon as we have some feedback.

**Comment by gowridurgad** [comment]
Hi @GabeGiro, After replicating the issue using the provided workflow, we found that everything is working as expected. The Build with Gradle step is correctly compiling and testing with Java 17. For your reference, we’ve included [link](https://github.com/setup-actions-demo/demo/actions/runs/12515123599/job/34912210143) of the successful run. To assist us in further investigating, could you please share a link to the build or a public repository where the issue can be reproduced?

**Comment by gowridurgad** [comment]
Hi @GabeGiro, Just a gentle reminder regarding this issue, If you have any updates or need further assistance, Please let us know.

**Comment by GabeGiro** [comment]
@gowridurgad  I'm not going to work on this issue for at least 3 more weeks. Although I saw your successful build I'm curious what is the difference between our gradle files. I'm working with a mature Android project (few years) so there is 100% chance something is different and unfortunately Android builds don't have containerisation - hence it works on yours but not on mine. 

Again, I will not work on this any time soon but if you can share your process in the meantime, that would be useful. Did you start you Android project from scratch, did you use Android Studio's empty project, are you using old or new gradle files? 
And I will write all these for my project in few weeks.

Thank you in advance

**Comment by gowridurgad** [comment]
Hi @GabeGiro, Android Gradle files include Android-specific plugin configurations, dependencies, and build configurations, while normal Gradle files are typically used for Java or other JVM-based projects without Android-specific configurations. we are using simple application using new Gradle files specific to our setup. To generate Gradle files:
1. Install Gradle from the official website.
2. Create a new project using the gradle init command.
3. Configure the build.gradle file with necessary dependencies and plugins.
4.  Run Gradle tasks like gradle build and gradle test to manage your project.

 For more detailed steps, refer to the official documentation on [Building and testing Java with Gradle](https://docs.github.com/en/enterprise-cloud@latest/actions/use-cases-and-examples/building-and-testing/building-and-testing-java-with-gradle).

**Comment by gowridurgad** [comment]
Hi @GabeGiro, Just a gentle reminder regarding this issue, If you have any updates or need further assistance, Please let us know.

**Comment by gowridurgad** [comment]
Hi @GabeGiro, Just a gentle reminder regarding this issue, If you have any updates or need further assistance, Please let us know.

**Comment by GabeGiro** [comment]
@gowridurgad thank you for sharing the link but it's not useful here. We are talking about Android-specific project. As mentioned before, I would appreciate if you shared some Android project files that enable you to build with Java 17.

Here is my setup:

.github/workflows/ci.yml:
```
name: CI

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-v1-${{ hashFiles('**/build.gradle', '**/build.gradle.kts', '**/settings.gradle', '**/settings.gradle.kts', '**/gradle.lockfile') }}
          restore-keys: |
            ${{ runner.os }}-gradle-v1-

      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Notify Success
        if: success()
        run: echo "Build and tests passed!"

      - name: Notify Failure
        if: failure()
        run: echo "Build or tests failed!"

```

Part of app's build.gradle:
```
android {
    namespace 'com.name'
    compileSdk 34

    defaultConfig {
        applicationId "com.name"
        minSdk 29
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        externalNativeBuild {
            cmake {
                arguments "-DOPENCV_VERSION_MAJOR=4", "-DOPENCV_FROM_SDK=FALSE", "-DANDROID_STL=c++_shared"
                targets "native_lib"
            }
        }
    }
    ktlint {
        android = true
        ignoreFailures = false
        disabledRules = ["wildcard-imports", "no-wildcard-imports"]
        reporters {
            reporter "plain"
            reporter "checkstyle"
            //reporter "sarif"
            //reporter "html"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    composeOptions {
        kotlinCompilerExtensionVersion '1.5.1'
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
    }
    externalNativeBuild {
        cmake {
            path 'src/main/cpp/CMakeLists.txt'
        }
    }
    buildFeatures {
        compose true
        prefab true // Enable prefab for OpenCV
    }
}
```

Please, let me know if I can share anything else that will help you solve this.
