### ISSUE TITLE
Backport older Java versions

### ISSUE THREAD

**Issue by aep-sunlife** [actions/setup-java#721]
**Description:**

Support Java 7-.

**Justification:**

To benefit from GitHub Actions and convenient setup-java workflows, concurrent with efforts to upgrade Java in legacy projects, e.g. scientific applications.

**Comment by priyagupta108** [comment]
Hello @aep-sunlife,
Thank you for this feature request. We will investigate it and get back to you as soon as we have some feedback.

**Comment by skateball** [comment]
Hi @aep-sunlife ,
have you checked which distributor is still offering java 7 releases?

have you checked already if the following might work?
```yaml
steps:
- uses: actions/checkout@v4
- uses: actions/setup-java@v4
  with:
    distribution: 'zulu'
    java-version: '7'
- run: java HelloWorldApp.java
```

Regards Christian
