### ISSUE TITLE
Allow to configure cache scope

### ISSUE THREAD

**Issue by ale5000-git** [actions/setup-java#726]
**Description:**
Please allow to configure cache scope, example:
```
      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
          cache-from: type=gha,scope=global
          cache-to: type=gha,mode=max,scope=global
```

**Justification:**
I have a workflow that run only on tags, without specifying scope the cache is never restored since every tag have a separate cache.

**Comment by priya-kinthali** [comment]
Hello @ale5000-git 👋,
Thank you for this feature request. We will investigate it and get back to you as soon as we have some feedback.

**Comment by brunoborges** [comment]
Thanks for the request, and for the clear justification.

After looking into this, I don't think a `cache-from` / `cache-to` scope option belongs in `setup-java`. A couple of reasons:

- **That syntax is Docker Buildx-specific.** `type=gha,scope=global` is how [Buildx's GitHub Actions cache backend](https://docs.docker.com/build/cache/backends/gha/) is configured. `setup-java`'s caching is built on [`@actions/cache`](https://github.com/actions/toolkit/tree/main/packages/cache), which has a different model and no equivalent `scope` knob.

- **The behavior you're hitting is a platform-level restriction, not something `setup-java` can override.** GitHub Actions [restricts cache access by branch/ref](https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache): a run can only read caches created by its own ref, its base ref (for PRs), or the **default branch**. That's why every tag ends up with an isolated cache. No cache-key change we make inside the action can lift that restriction.

Given that, this is an advanced caching scenario that's better handled by driving the cache yourself. Two options:

**1. Seed the cache on your default branch.** Because the default branch's cache is readable from every ref (including tags), a scheduled/push build on `main` that populates the Gradle cache will make it restorable from tag runs — no extra inputs needed.

**2. Manage the cache directly with `actions/cache`.** `setup-java` already exposes the computed key via the [`cache-primary-key` output](https://github.com/actions/setup-java#caching-packages-dependencies) so you can compose it with `actions/cache` / `actions/cache/restore` and take full control of `key` and `restore-keys`:

```yaml
- uses: actions/setup-java@v4
  with:
    distribution: temurin
    java-version: '17'
    # omit `cache:` — we manage it ourselves below

- uses: actions/cache/restore@v4
  with:
    path: |
      ~/.gradle/caches
      ~/.gradle/wrapper
    key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
    restore-keys: |
      gradle-${{ runner.os }}-
```

For richer Gradle-specific caching (build outputs, configuration cache, read-only/write-only modes, fine-grained control), [`gradle/actions/setup-gradle`](https://github.com/gradle/actions/tree/main/setup-gradle) is purpose-built for it.

I'm going to close this as not planned, but happy to keep discussing if one of the above doesn't cover your case.
