### ISSUE TITLE
Cant find version 21 jdk for adopt.

### ISSUE THREAD

**Issue by counter2015** [actions/setup-java#784]
**Description:**
This action works fine several weeks ago, it now fails with `Could not find satisfied version for SemVer '21'. 

**Task version:**
actions/setup-java@v4

**Platform:**
- [x ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x ] Hosted
- [ ] Self-hosted

**Repro steps:**  

The workflow file:
```
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

name: Update dependency

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Install sbt
        uses: sbt/setup-sbt@v1

      - name: checkout
        uses: actions/checkout@v4

      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-app-id: ${{ secrets.APP_ID }}
          github-app-installation-id: ${{ secrets.APP_INSTALLATION_ID }}
          github-app-key: ${{ secrets.APP_PRIVATE_KEY }}
          github-app-auth-only: true
          github-repository: "counter2015/tccc"
          author-email: "43047562+scala-steward@users.noreply.github.com"
          author-name: "Scala Steward"
```

**Expected behavior:**
It should work well.

**Actual behavior:**
Action fails with message following:

```
Could not find satisfied version for SemVer '21'. 
Available versions: 19.0.2+7, 19.0.1+10, 19.0.0+36, 18.0.2+101, 18.0.2+9, 18.0.1+10, 18.0.0+36, 17.0.14+7, 17.0.13+11, 17.0.12+7, 17.0.11+9, 17.0.10+7, 17.0.9+9, 17.0.8+101, 17.0.8+7, 17.0.7+7, 17.0.6+10, 17.0.5+8, 17.0.4+101, 17.0.4+8, 18.0.2+101, 18.0.2+9, 18.0.1+10, 18.0.0+36, 17.0.14+7, 17.0.13+11, 17.0.12+7, 17.0.11+9, 17.0.10+7, 17.0.9+9, 17.0.8+101, 17.0.8+7, 17.0.7+7, 17.0.6+10, 17.0.5+8, 17.0.4+101, 17.0.4+8, 17.0.3+7, 17.0.2+8, 17.0.1+12, 11.0.25+9, 11.0.24+8, 11.0.23+9, 11.0.22+7, 11.0.21+9, 11.0.20+101, 11.0.20+8, 11.0.19+7, 11.0.18+10, 11.0.17+8, 11.0.16+101, 11.0.16+8, 11.0.15+10, 11.0.14+101, 11.0.14+9, 11.0.13+8, 11.0.12+7, 11.0.11+9, 11.0.10+9, 11.0.9+101, 11.0.9+11.1, 11.0.9+11, 11.0.8+10, 11.0.7+10.1, 11.0.6+10.1, 11.0.5+10.1, 11.0.4+11.1, 11.0.3+7, 11.0.2+9, 11.0.2+7, 11.0.1+13, 11.0.0+28, 10.0.2+13.1, 9.0.4+11, 9.0.0+181, 8.0.442+6, 8.0.432+6, 8.0.422+5, 8.0.412+8, 8.0.402+6, 8.0.392+8, 8.0.382+5, 8.0.372+7, 8.0.362+9, 8.0.352+8, 8.0.345+1, 8.0.342+7, 8.0.332+9, 8.0.322+6, 8.0.312+7, 8.0.302+8, 8.0.292+10, 8.0.282+8, 8.0.275+1, 8.0.272+10, 8.0.265+1, 8.0.262+10, 8.0.252+9.1, 8.0.242+8.1, 8.0.232+9.1, 8.0.222+10.1, 8.0.212+4, 8.0.212+3, 8.0.202+8, 8.0.192+12, 8.0.181+13, 8.0.202+8, 8.0.192+12, 8.0.181+13
```
