### ISSUE TITLE
Jetbrains runtime uses pre-release version

### ISSUE THREAD

**Issue by amir1376** [actions/setup-java#829]
**Description:**
Jetbrains runtime uses pre-release builds even if I use version something like `21`

**Task version:**
`4.7.1`

**Platform:**
- [x] Ubuntu
- [X] macOS
- [x] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Repro steps:**  

1. use this action
```yaml
 name: Set up JBR
 uses: actions/setup-java@v4
 with:
   distribution: "jetbrains"
   java-package: "jdk"
   java-version: "21"
   check-latest: true
```

**Expected behavior:**

latest stable version (`21.0.7b968.13` at this time) should be resolved

**Actual behavior:**

In the action log you will see that version `21.0.7b982.16` is resolved which is pre-release version in github
