### ISSUE TITLE
Gradle build is failing in Github Action, but passing in Travis CI

### ISSUE THREAD

**Issue by anidotnet** [actions/setup-java#89]
I am observing one issue with setup-java action. My project's gradle build is failing in junit test while running on github action, but same commit is passing in travis ci. It also passing in other linux environment.

- Github Project Commit - https://github.com/nitrite/nitrite-java/tree/ad3afc0641efc9d8425ac2ce59a037b00f5ccda9
- Travis CI Build - https://travis-ci.org/github/nitrite/nitrite-java/builds/717209688
- Github Action Build - https://github.com/nitrite/nitrite-java/runs/975425910?check_suite_focus=true

And here is the workflow file - 

```yml
name: Gradle Build

on:
  push:
    branches:
      - 4.x

  pull_request:
    branches:
      - 4.x

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8.0.212
          java-package: jdk
          architecture: x64

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Prepare PGP Keys
        run: openssl aes-256-cbc -pass pass:$PGP_KEY_PASSWORD -in ./.ci/secring.gpg.enc -out ~/secring.gpg -d -md md5
        env:
          PGP_KEY_PASSWORD: ${{ secrets.PGP_KEY_PASSWORD }}

      - name: Publish packages to snapshot
        run: ./gradlew publish -Psigning.keyId=$PGP_KEY_ID -Psigning.password=$PGP_KEY_PASSWORD -Psigning.secretKeyRingFile=~/secring.gpg
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
          PGP_KEY_PASSWORD: ${{ secrets.PGP_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.NITRITE_GH_TOKEN }}

```

Any idea why it is failing specifically in github action only?
